apiVersion: v1
kind: ConfigMap
metadata:
  name: model-train-config
  namespace: model-train
data:
  apps.yaml: |
    apps:
      mlflow-connection: 
        url: https://mlflow.icantkube.help
      redis-connection:
        url: redis-master.redis.svc.cluster.local
        port: 6379
      minio-connection:
        url: minio.minio.svc.cluster.local