apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-train
  namespace: model-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-train
  template:
    metadata:
      labels:
        app: model-train
    spec:
      containers:
        - name: model-train
          image: icantkube/model-train:v0.5
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: mlflow-auth-credentials-external-secret
        - name: celery-app
          image: icantkube/celery-app:v0.1
          envFrom:
            - secretRef:
                name: mlflow-auth-credentials-external-secret