apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-train
  namespace: model-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-train
  template:
    metadata:
      labels:
        app: model-train
    spec:
      containers:
        - name: model-train
          image: icantkube/model-train:v0.4
          ports:
            - containerPort: 80