apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml
- rollout.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
- mlflow-auth-credentials.sealed.yaml
- horizontal_auto_scaler.yaml

images:
- name: icantkube/model-train
  newTag: v0.43
- name: icantkube/celery-app
  newTag: v0.22
