apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- mlflow-auth-credentials.sealed.yaml

images:
- name: icantkube/model-train
  newTag: v0.23
- name: icantkube/celery-app
  newTag: v0.2
