apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
- mlflow-auth-credentials.sealed.yaml

images:
- name: icantkube/model-train
  newTag: v0.29
- name: icantkube/celery-app
  newTag: v0.8
