---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials-external-secret-reference
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBjBkUuge3hGyWtjwC61HAtTXKmGz7oiPhpDavWGL7ZTZ7F6iQZKH9GqKnD+eB3ZNUR85gl5dKrhX23RLUxzpaTnwDFGfmrjZqED8LixO6mQR/x9MrqRSiKcrMmtBLTCMc79HSXo2ref+LkQ9d291Gwq8Vs6YtPEXMmELQdOwJvj+i0YTVliqVjrA/nDrVPTHZb3mL2UwnqydWstslsvetuSajoSzHEn9KtCUPrc02Jmot6mRf7dlXmmv9WP3ecDjSVLNvWPN0bQc8O90OrExAMqNvIFNW43eRCTB6XT4s7Ip+rOsA0nWT3E2Wz8e8cZ5rtGfAKZ7T5PoLjH0dRhMir7wv16RBtRy3HUIV+yCZ7H0/oFYf+iCcq2vgnIboMWQiSN6714Tf/05dZADJ+/a/atRdGWMaCRh8EActCRpDV4888Jpk48Y0ceGFmbF5CHem9H2Y+Ee39YJ5h9KNOiwRsOqE3BlTK9Ehm0Hi+2WaNfUsZrXzW/NPZm51oZ/wLagZod+wIoFvFKXQ5TJ6/fngFDyhSQdz9TuCeOxXw+H9wDVe7u5NX7ngO20vLkJdyA2hPA1Q+3dQZvyY3jtIYpjjBjPapUp9tSQesJs8CF1rZFeAVG2XNDm62SaZDZfRiMw8qzI2yhLeo2D+ZilsAZh3xHQMKa1Pb7xuhEZHSJvz+rbDlskSJwlBBkkJSWs10sOtmw91F3rW1h3v3Y2bLfQE=
    MINIO_ROOT_USER: AgBY3rCt4CPpbDI5rPmHSF1ctJaBeqGx1/TiU1s+oDck0ieMb5MusAUHPLpBIMeblNYIF3mpfUIGnZjwO+3cNI4/b9YpO28KTua5n3vxqTSBB/XAQeE59nzn9ADTs3MJ02IDTVW7A48eFsmYxTZabi0+pkByZAyCkk7QDn01nOO4tC4b4fww03noTssdrF8TxXno5zF25cwhmX3pLq2wabB+s5iQ5Fk4dHWNEMRrRSHBN0ZNKOAq7j60+b5XJagQIbHyFjqmdeiQt0GqnCooazMX1eKPAOAWRQDClNHvUq50LFeg4+zPT80iyx0SCTuHe9vMVfV5eZw2ZMvO98u8wOWygvwCeerWVBzJsXxLh/Rmz5hUi4g0C/8nNZIMm0EnF2SaUV21C9+NsOoqBRBilNVe4TFY+TcGOsEgNrbc9WftG7A96ObgS1vaCsdLgDvteCydw4SJGwRa4WeYJHtLoq5Do1dVbQ2jwJ+l79XgJiCWRzDKG4uinKc7H1z2V+ZJlvKy4PMmnSwgXNSAYBGICsDX/+dEwGdPhTR78pmGWMqYjLqy4jSnssXJhcxjNq/bwFiMLBVf6BgVkHrSPGlDXVIZ8TQTUvvAnBz1F5r0g7gj5WcgiaYUNgjKqLgDCRNPhspSLAm8lWgFFr6VmxMq6sqp9YMruEx701vE7UExGT0oIk8dzFel36ywnmS5b3fLm9EYNUm1LA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials-external-secret-reference
      namespace: minio
    type: Opaque
