---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-auth-credentials-external-secret
  namespace: model-train
spec:
  encryptedData:
    password: AgBJzHJt9beCiEnraTY9+VFZxlWOiZ+tTppk9qOg/sXVzpUV6oZZPOa+3M0O3Sz0lEqlKEXRguGDtCYQEyJtcNWYAi/TSFig0kiCb9DbsmxYScLaBZHmYej11NAXuFtv9TpkRYyvxLgN3VAZVc4+uviXYIgQBTlV+EiP43lCOQgSIi4+puJlrYa20UDaYKf52eDBn4+mxTnzwcgpgsS1BZwI+c+nE6e9ZbmJoWKm+Zqg74J0p64EXh0r4TsN6falwTDeC5hDx/I0DDqNmHaVk1r7pzv1tIB9raJQPvWzUm4myEgL/HU73EAzFzvWdGQPxAmoZfE0baEpJuXQJAgmTiqhnzcLOpckVTMmP2G+MaI7sAu3QGF24QDizntiMUpRq3shsy2ct+V+aY7IjB8nucAudxTTVQ5IKCxfyb1SU8GmtyQR3tKJG6ahg98TGMzDorLg54KBsBIHOiX6Zu0eXrVSWrIzFg5piul+B2BVi+HKC2U6aTWSIADz+HXuJvGCdAcIPCP5yj6cXDaVcDvN/GaYolTCA2lTO7m8T4tojchrOlIc9Aiiepto+d4afLsF1xXdrifLx9fTZzmghLn826BvtG6M40VUIhEWIVebW91H66VFbRksOhf68KMMLvVITmKnF+IjZpB4DaAKIaL5YyB6dvC5mITcFH6Mcenl1w4FuqGLqMGikrubzFaCMMaOYsO1VIQlvnyib9eB7izTO6g=
    username: AgCF6JHsh5YV3Z8pDunVVHONLhf0z1pQAz4V7jzLSswAZVgo+DSBROX+LTeZx+bzLQiV5DM3SBHCN54mwULm6CsdERGGclbxlTVRyxH3BlgbzEddZUV6TCQWmMSkmp9O62e4ls+tM2ng4fxsHNrJdVTLA0mdVkQEngaLN3GQNUC+ajpMaVPuVYr6abQu50krae8Rc1BahV5U4Wq0t+Xh/imLPAGK9VP8eiz9XYqEF1BxelMUL6LgEqSY6dibPC18qinEjXrQYpb65BvWZzOQmvEZJmNuXD+YsMsPJ4AEPghAWGH2FCj7S6m8prb9NBnp967ZJ+ocXhTQAj3mqqNfBtrnNg/d2RL3bJTV+so3KNAoguJ7pygRMdJ0VdLAagkPnW1eZeUe0eKn24+M2ehlEJBBCcQ4BpWQjSjObctuXOu+75zN8cllpqGggGHDNUX4Stx6MesL5a8pEmhpzANw6iJAt9iULV1yWwVde90Hb8B4z/0CpKHhkO+V4uXYZmF0foJ0MVQd+xHtZuXp0Ry9eW8Dtc+CBSyXmM40rFQNEYh+u7UcrvulGX+fYG1/14+CRiUt3IKZJRlZ48E0qzguXo7ERymm9nH4PreZpVIyr+ZhDLzlLXfaciqVVFAu1cCmfr0bJi0iC1+/Yhvnr9bQgupJqbLrX6Y53IMCiBGGVY6SABOux4SiMorBkNb/sFVYfKc03tpY7A==
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-auth-credentials-external-secret
      namespace: model-train
    type: Opaque
