---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-postgresql-credentials-external-secret
  namespace: model-pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgB9Zrk4NIvxKALwuVNQ85rMFUcM5cjm5tjyqx7cOZ1QdwitA4izfGflR3LUg64WdQrO87ucbLFCC9smFCWVRDIoanlPO+KmJ4AIgVxjQBQFc8oV+i75yxTaASNNOpjeZm/Ta8HfAdb0RgjwqZFFZ9cyP0+g6nrgt7xylIODkw8A+H11qndzXMhXh/rnluawjb54eKFMBUw1JzCt2b/9/5qNPNyzUHD1U2HJJoctLjfIrjDqso/ldGndKF2k6dAzE2rN8IytvY4txbBy0dfwXmOA/opsDiLhuuFQYgiJMV6uJqC0xADACvemIbmZAnAnCmN7aevhzyEnY/+yBYcO4NI+Vqf+BuDuZUa+PqLeE8lgSvjZQXylHUV+z131h075y4HIs4JzA/SPGUnS0CGm6Q79l+wsdly3O8+rWVU5dWk8cCZwNCZS34ZR8mWC5iexcM176Ww/eyotQrr9xIZsLugpDUHtVyrMCKEiDQeCRB0VmZL7uRZInod8L6Mix80zcn2j6alrN76i1ITI2XqpeIqvFCt9FolkH0YzrfexxKUfeEiUIvvLxHRWO53mnWjM7jcUMgyBJFNR2ZCsB6d2hbH10zZ6/1UlwdVzqydFRyVpR4g0holYSBHVuThiEffrT9aZUXW4SW6P3hGLMpvBoLTp9s0zP+F/H+rAnAfrd434ks6E1T0eKEtGcq73SjWW7pWHFzf4W+p/rLeP66evfaE=
    username: AgBNxKVKcDvyjawFbgWopjDho9muFNUI9fGWyCJz93q+jI/E7oKfa1Q/K9XhcuVA/nyvFdepOFu5ToTDtDvO1Ximcz7fmc/Rph97MQjiw3Vs/EbEyrluUuvu6jbijYfJ+qGqsBmi897buuy2DNNgyg9YSfA5MXGingGYTt5Z+VOEnhgtKg7fhheFUeJhbwG8E6bl23dEgHZvHbXM6gnD4p1/KKEEpTu9n0I7VJmUTLU2ug2yyhT9f2LUbx41iGmNpjCU3dh8eGAvZgZasoDXMi/zZrIUKOa5OA6ycelH+G+PIpDfi5PES00BEjJCjYyfLl1WugvWt0pLHUn0REPe+ZfjU1PyIxXVHEZXBLdYg9awON0ovmvcegiQDNZ1XC2NPl1EaaTDxnbKDBP8oi8F6RmHimoRJxWiBhC9kci2qrTokiVS2UzbUnf0f/c6LQxHwUetWcBOUoWNbDdyqzIUk8wM7iMBwSq10mzARbV9BlAuq1/4+Qe4xrUWU3fDo3i7vmSf2Dth9HZrHqAJpi4DOOUPY5pI64117H8VfW4Ed40DPezC/2OqEK2MVUAH6QrcPTOCn5yEgjZNiamZoLROLWxtEv/qY53r60konXgVrggUxgOH1FOQ7XYVeIkcoSXTAIfU3ujZWr9Np2+a+bwU2gYXNIGTBKj6rt9nYOt6S40gHAihB4FBO0CYeTBJvu1tUY31aSFtY2s=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-postgresql-credentials-external-secret
      namespace: model-pipeline
    type: Opaque
