namespaceOverride: model-pipeline
nameOverride: mlflow-postgresql

auth:
  database: mlflow

  username: mlflow
  existingSecret: mlflow-postgresql-credentials-secret
  secretKeys.userPasswordKey: password
