namespaceOverride: model-pipeline
nameOverride: postgresql

auth:
  database: mlflow

  username: mlflow
  existingSecret: mlflow-postgresql-credentials-secret
  secretKeys:
    userPasswordKey: password
    adminPasswordKey: password

