namespaceOverride: model-pipeline
nameOverride: postgresql

primary:
  containerSecurityContext:
    runAsUser: 0
    runAsNonRoot: false

auth:
  database: mlflow

  username: mlflow
  existingSecret: mlflow-postgresql-credentials-secret
  secretKeys:
    userPasswordKey: password
    adminPasswordKey: password

