apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: busybox-debug
spec:
  strategy:
    canary:                        # Changed from rollingUpdate or recreate
      steps:
      - setWeight: 20
      - pause: {duration: 20s}
  selector:
    matchLabels:
      app: busybox
  replicas: 5
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.36.1
        command: ["/bin/sh", "-ec", "sleep infinity"] # Sleep forever to container alive for exec
