apiVersion: argoproj.io/v1alpha1              
kind: Rollout
metadata:
  name: busybox-debug-rollout
spec:
  replicas: 50
  selector:
    matchLabels:
      app: busybox
  workloadRef:                             
    apiVersion: apps/v1
    kind: Deployment
    name: busybox-debug
    scaleDown: onsuccess
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}

