apiVersion: v1
kind: ConfigMap
metadata:
  name: model-train-config
  namespace: model-pipeline
data:
  apps.yaml: |
    apps:
      mlflow-connection: 
        url: http://mlflow
      redis-connection:
        url: redis-master
        port: 6379
      rustfs-connection:
        url: http://rustfs
        region: us-east-1
        signature_version: s3v4
        bucket: datasets
      mariadb-connection:
        url: mariadb
        port: 3306
        db: machines
        table: machines
