apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml
- rollout.yaml
- deployment.yaml
- service.yaml

images:
- name: icantkube/model-train
  newTag: v0.93
- name: icantkube/celery-app
  newTag: v0.72
