---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-minio-credentials-external-secret
  namespace: mlflow
spec:
  encryptedData:
    access_key_id: AgBKxu+gKtpaNmwMB7PXqeS9+JJe0ibyv/XD0Ucna5Zz4igvD1b2tNBQS3p5oGI0KjmyUqQhU+zRi6X+2FPW9p5cRi6877kTo7o1exZl//Qm3JTA7SFTGM5u/LaeNyeoRNBZX1CxgBowAfTD7dFnWyxpYeVbWo1qd6YAe878NGIo37+/AzkqLYb6OmHSiib+BluXTaiuG3fvBzmW3zuJDkxoyKEq2QCFSYqtIyj7BT9Sf1VU7yTOMdElTiZL1+WimH1avdsykAmD5woCG5omC2At0fu2y+0699i6gLzUXBNroLwgNBwWLLy4JdGFRvlyR1DWGTUUNy7ZQBZwOzu2OGyJSXXCviZf8DcviBVb++lmiT4VD3hFonX+e/Ml35EfJhwwerr/mQdNaWlbLaprBOF00Pbp2yeB1+FutFQocvbZoDU00vgg89k5BNWE8HZTJClndCHS6YFyayNuq4EA5tmfvl3ZEIzWI1+rlVFcXRD/Xnpx88Du1AuDPpkQGs4zW8uGWeCGyGjJCEONsMScHPm3v/bXsakKciwyry474teHKrQOPHB3IccvDrq0Qv4WNpDfJ8bYCYZXffcV/VI+MITu0II/4Xth+Ykt5S2f7E+6s3k+DxX0ElTqw6ozQxlhuDdRJUzb5/3xj1gbm9eQnGTnLUTg9bh75XdR8nXA+mITi/wJtlnJNwUhs3Po2LYium/U6C26Ww==
    secret_access_key: AgC6LZGpFQMtALpVQakXmujKIvdcnpbDFPbruOCgPis9QrbmK4HUo8K9y42l1kzjmXf0aFJ0xnVwEuTD1SGfIQTh5WnzZTgiJh0FzYjXSO65HblINEGaqQWGypBWYy2Mof959idDv74A+9EFUVxOVhtwLzE10K0EAE3uVRXO4CczNLKW/pbRjoR3oNW/dpi+sKQ38RQumUldF1Y0D37CJTDxyazZMYp51YRvdDTuzOzMVPaWm3/R+4YsAT5s+f6e3e38EQ2sx7DiuiedeoyG4Oibv5mydry6LJbCUMhx+FLcmrmG3BPZFGp4Ic0o/b7JJQ/CxFWl1dQmzcGyofmkLUNHvWbHPE1EAuAYaDZrwZJN6GQwvyRzwk+luunadNqlIR7OcIL7Pe0rmkP4EfWgbcUTOq3t5LLZRa7QKi30VS1j+iiPhsBdun0ZlgaJTBD90b+DliQ0CJS8LT+C8IbAYOvcdp0D9vrsSmI6uuosWOXq6suw0YA73yIKn030qs/Xq8xYhS3j6EB4EjD+QLnIPp3ai5lVWztadGG2o99fHn7uKuAE7Qr939yzuwVnzcWwLv+7TTXv3d8OvmqvYMXIywOmTS24v7OyoTaKOn2Lbob4pIzaSYXxC+FEq7tjxJTfpL7ZQvuvKZD1HecGqvfhFWnYJaP/dAkJHDHP8Fwy6hXOObVKmDcRHA2Lu8UvM9mkPdXruMblwe4=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-minio-credentials-external-secret
      namespace: mlflow
    type: Opaque
