---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-minio-credentials-external-secret
  namespace: mlflow
spec:
  encryptedData:
    password: AgCBUDKm59FS+c2X58qih9/HeesV81naoo3G7G46ehNNK0GNyNulerZQdj1BAdFSis06kH8BQzdd+joL63LSK+L6+Py3hW6pS68fT5+ZBqjKT8oBeZ5/w47zkYW3w4IiMCyN9lEFZ+Ok6/5Jw5aesZ+Bj9EWWxz8bXdm5inEg2EEjufALpDt4JTjIhRr4Yquapu5UndtR/Ns76/xhf+ea0gTiU7l4e0ed0WP3BXaEXei+bPhlwxwMGTjFDOU/kkrhyrL7kosRYRQjcqMDVXA3AQ0Uv/54HAKWwyQiLxKtMildBYT1Vilhz1xEsU6yu4w90/t/vgxq98QJXOmonya7F0s6IAYFgmdIVOj4QLdxE/rGjY5m0lwvFW0OpDs5fNtSCIgzJ6uYuAl9gNNL16gj32xPl0r3NQnIIcuacPbqMviKsfbeKI+WCnDmq++o4NOI+HgHETV51I4yoJmqmJYbyNMNSBRedRVCqwjdgNidgUMl0iw0uDCaNwidJqlUTNLGmK1QBExbICAxH2hNur+bfeGub98adf4eaKM0+RyGum3bBjwMP042TGNbU8jeuzqG14Al4QRrmKyriHE3NbwrskPhhpvrXE1AAT8XC3CzVOsscS+Os7N2M6QGW30k2RgFQvEHYTPK9Ib0mXUCcs+utWnxjKZyDt2S4dHCcTYgu7V5UKqE6gHu39CRWdTJCLt8Rge+g3HTgnsZUxz0rY9TZSI5A==
    username: AgCE/5YFUqp/VBTu2XLVtpLH/jNkhL+46+tyTjXe+wOBd4pRfUVXajW/S5r2lz3s+4bZLcWCS5nQlis1anKEBnbkycJVFrH6Vy1XwC2598W2+UZ8MCSiIwA+pYK8s+nRBB45vEn7aLfNGpmZx5Akpeflk/IN3n5nTlEZrq13XbDP25uYhpbGRV9yQIUJLLsX1OC5OO2y4UzmBtC2mOg+USk07D/DcPZ4ByQTAeN0zkhry33C5tU9jfcIyY4uJgWb/nMwlLpcEWbREWqOoKkRqhAVWO+byBbKwentUfzAmCu6oxxjBXR35CmOS6m272RD0030f8NGtmA+rvrTeWl9Cxd1UR4AybN8LPQlimr6GTxvgEshaN/IbZosIJG3ZyhZzOzwIT3cNTGja7p+8CUHjiE/KKbth2G0SPpVeZwlSLqtlLSmW17gyW0xwt9TIolwzR7ABGwrSQ9lR9ARMPIumuOKcu/jWkrV6KVNcShQCKNv9L4DIolAdbV8iL0uJ1bxrbDFwQfEovFEKeagCbpZ2Q+Hl1OAF0wfOmQVUno6OFNgCQi55rX7ARZy74HvvKI2AelaeG+fJuXF3SVacNZNIsKAGggt6rJfED5thPEnnu7vxj6a4qkuX34cQlxxI1XRV2xHaD7/SFc3w+4a0lwPbDJqjNIcJsjeLbgXEiP91Tsb4ih1QSo8Or+84d2wgis395IG6gjHy+37DPmfoblG
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-minio-credentials-external-secret
      namespace: mlflow
    type: Opaque
