apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebox
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
