api-gateway:
  autoUpdate: false
  autoBuild: false
  currentTag: "v0.1"

frontend:
  autoUpdate: false
  autoBuild: true
  currentTag: "v0.3"

model-train:
  autoUpdate: false
  autoBuild: true
  currentTag: "v0.3"
