api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.18"

machines-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.99"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.78"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

sensor-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.8"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.38"

model-inference-server:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.32"
