api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"

frontend:
  autoUpdate: false
  autoBuild: true
  currentTag: "v0.5"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.27"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.6"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

machines:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.2"
