api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.5"
