api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.5"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.21"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false
