api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.19"

machines-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.101"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.80"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

sensor-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.9"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.46"

model-inference-server:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.38"
