api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.14"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.29"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.8"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

machines:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.2"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.7"

model-inference-server:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"
