api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.18"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.66"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.45"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

sensor-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.2"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.8"

model-inference-server:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.5"
