api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.18"

machines-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.2"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.83"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.62"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

sensor-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.6"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.8"

model-inference-server:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.5"
