api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: false
  autoBuild: true
  currentTag: "v0.5"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.28"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.7"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

machines:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.2"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"
