api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.19"

machines-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.3"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.102"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.81"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

sensor-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.10"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.47"

model-inference-server:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.39"
