api-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.4"

frontend:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.18"

machines-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.2"

model-train:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.87"

celery-app:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.66"

sample-echo-microservice:
  autoUpdate: false
  autoBuild: false

sensor-data:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.7"

inference-gateway:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.9"

model-inference-server:
  autoUpdate: true
  autoBuild: true
  currentTag: "v0.11"
