apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml
- deployment.yaml
- ingress.yaml
- namespace.yaml
- service.yaml

images:
- name: icantkube/api-gateway
  newTag: v0.2
