apiVersion: v1
kind: Namespace
metadata:
  name: frontend-test
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-test
  namespace: frontend-test
spec:
  selector:
    app: frontend-test
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test
  namespace: frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-test
  template:
    metadata:
      labels:
        app: frontend-test
    spec:
      containers:
        - name: frontend-test
          image: mysticshirou/icantkube:v0.1
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-test
  namespace: frontend-test
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: frontend-test.icantkube.help
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-test
                port:
                  number: 80