apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-test
  namespace: default
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: frontend-test.icantkube.help
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-test
                port:
                  number: 80