apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynamic-localpv-provisioner
  namespace: argocd
spec:
  project: default

  sources:
    # dynamic-localpv-provisioner Helm chart source
    # https://github.com/openebs/dynamic-localpv-provisioner/tree/v4.2.0/deploy/helm/charts
    - repoURL: https://openebs.github.io/dynamic-localpv-provisioner
      chart: localpv-provisioner
      targetRevision: "4.4.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/core/dynamic-localpv-provisioner/helm/values.yaml

    # icantkube repo containing values-override.yaml
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: kubernetes/apps/core/dynamic-localpv-provisioner/

  destination:
    server: https://kubernetes.default.svc
    namespace: dynamic-localpv-provisioner

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
