apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default

  sources:
    # sealed-secrets Helm chart source
    # https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: "2.18.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/core/sealed-secrets/helm/values-override.yaml

    # cantkube repo containing values-override.yaml
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: kubernetes/apps/core/sealed-secrets/

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
