apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - horizontal_auto_scaler.yaml

images:
  - name: mysticshirou/icantkube
    newTag: sample-echo-microservice-v1.0
