apiVersion: v1
kind: Service
metadata:
  name: sample-echo-microservice
  namespace: sample-echo-microservice
spec:
  selector:
    app: sample-echo-microservice
  ports:
    - port: 80
      targetPort: 80