namespaceOverride: argo-rollouts
keepCRDS: false

dashboard:
    enabled: true
    ingress: 
        enabled: true
        hosts: 
            - rollouts.icantkube.help
        ingressClassName: cloudflare-tunnel
