apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rollout.yaml
- ingress.yaml
- namespace.yaml
- service.yaml

images:
- name: icantkube/frontend
  newTag: v0.5
