apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-env-configmap
  labels:
    app: mlflow
data:
  PGHOST: mlflow-mlflow-postgresql.mlflow.svc.cluster.local
  PGPORT: "5432"
  PGDATABASE: mlflow
  MLFLOW_CONFIGURE_LOGGING: "true"
  MLFLOW_LOGGING_LEVEL: "INFO"
  MLFLOW_DISABLE_TELEMETRY: "true"
  DO_NOT_TRACK: "true"