---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-auth-credentials-external-secret
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgAdz9g+Efb/o2kQbpEIcYDzdzimUAEA/2E6x2Na468zy/WnCnsLWPeMpyQvuSi2D60h7U0AexOn6VdtZMDCKRso3gylR5pVXwxvqAT38hqXiWgwR+HgjZvWeEGbCrHJc9oiFl4RnnvooDI8Fn7+KTsXfrUGnDrjO1EK8pVfybVaHLgDG5LXL9oePH1hIGUvsItbseyKMPoi0hfukx+Os76Th9gZu3xjqGW+nV3EwWv4d19/KxGJk3yo1C1OI1wY/kIukzAfBUBRB8NOCcqH/Effu7KbEp3tOVAPeHfiyxmShgvglb29WSNmXP5LYfDFmsOSQDyt3Hd+BnkVGAz+Cn0Qszd0G1StWHZgOouEbLd8DDb6dW5I10DNDcJCxRr27E0XOu8PzAUmbBRpXy8n2x/NzXts+twDIv/47eWiZefQg0frHBveO/OwewXb+wAv2BumD2LMZ5EwoqoS6pvvk6t6OzwkOkS3exJHp2oI/AEqfd4CtxCdfUWfDBEqtCSd3cjGVERRw0sg37woA7IQp2DO8DSq7a/empVbCzpzjppIAlQZaa1GA592Yng4mpaXEcN5aNdQEc7kD+gdLPnmKGjLFzFke/3rESmt5VtOQ39Ok/z3O840yJgLKrfFzCNoBJLNERJF0zVetbE9jLfSk4Pbel2VGJHbkj0REN7FM64GdTyyWs+OiuB7J0pXzffq6dkMuFdQsT5P+goicKqVtbM=
    username: AgCSCOH7s2VbRXwHo9wM3jo+yJuYNky6g3JTKlUD+lnMoWgBDVk9mA9s12Wdp1UKWvg4uSNGA+D0C2phZJBK7FiJThpDyg/WVdDH//FgfYyNAC+C8hSWxvNL2Ov1/x6vRtoTNcNqNp8tDLGx45lzGTHlnYGmmCILgYJ54utpvVXch6vKYIgxpQJ2BcfPih5N7as43NKEtMIWUMm2NqVDXk27l8OZEmsSgkPr2ohjEfs77so0XOTQixxYmQvWVne1Sq0iYYhvxsE1UC2jvvX/lTs2/MjXxnbY/KuACx+pr5k3jgQCrj4u7UWz6qmgPOrZ00gmJM1nsGgjGqetgzmfmF3TtK/FFUhq/h0dxEX98rLXHdPgIu/bLU29kRX9vLnsCOfCSphlsiTAsnqM9EAb8d9jKUTqJ5vLPwkmZ5rLtOTDBA6X7jU1jTkmVMMyNGDJOxiF97ZM1deCreIRHEEl0sYy1GHQSTW9gp5gO0KXwtTNsOQc5x4H8FqnVg520kCvGmQFD7/pvyMUS7IIHLKStifUNcGWOtzbpgW32U6aWqK9+wbBNncxVyllCVbCQmqfpLvDD5GxmLAszCGXEdC0At6m5S7sSkLd8GDn6xCd3qIgEC9A4XyvUKUBej6LbJlv+XAHwicSup12NbhuxiYHgRUqpUWN8ue9E0ULvyOLaNMtB/UtZkjefKnC1KxtrTQuG3EFCkMuCoY=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-auth-credentials-external-secret
      namespace: mlflow
    type: Opaque
