---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-auth-credentials-external-secret
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgAkPi6PMKBCnutLGS5Ni1fe6ml6tA9f6jH2TCv+8LIo8RKW6FmFVJi9fC7EOXpGBRH60bFvfJXsdb2FHfENsV/J4IAnb+vu7hRrNas8hlLBag8CFlPhg4iW5iTK3diuppFYU4XFMcejGLi2VCp5PtN+fM5odNhf9z8W9PtP5HQ02AckD65nDthN6B9GuuXdSZmVkSDxLns4+JfVGtv/+IZMG4vHcUkrB3lxOWL4umZfTGEaZ7c4WvR4IPbYpAlZCPoTTFyKP2ZcLb/bjk860h35BsVSsLDGY6Ld+9Nrrf9IWHGw7Ydht/wmCYTjjHK9DaMd40FyHbjbXIYBxBvpyNzS0EUWmWNejJmBLsmI6ihD0uLfDktNDZc1euKcLAiAosu4subhTVh2t/Fsjw6jVAnfj7wchE8c49AOOZPlrIsqwgIm3tCpn9TDb1iLfP+zo+o7l9MgJnN6NrgjfWi1n82tg8TLTqxB9ZWoY9flBaC7AejOfG7IsUMGqyKVaGo6MgU+AUisdyGsgPWo7uY2kKXZYpSU4ECCHvagV8asocYXYMGxHLChrbLkHFxFRf9CXt4zFjdxl5AoqULlPjVN3Ex5vRHe1Aae3eJlbAb5DXu/0xnSK/Omg2J18608gZ+GKmLuft3qthkRL2jHtggrK3bc+ecLHOJ4jfVY5IbPq538eQvhjm1GxnKik6jawgZf7FjSVW1vbnuB/L3ZKwSSCX8=
    username: AgCN3JxIVODHMQUDBMSWHsU4l29MrNh3+t4X8Kdet4CEl/JinGVWgRup71H1d+s1FEq2uA8GjelVUNTmqFp+zY7fvkPyGoe2Lq016Ia4B3jTaD3ij+uTa2rb3zUnM5NzGlJU+I0MpjMqyy67FEBwarIwzjNG5Z/4nEQuab4r6jXMcEfZ9tMyYidHW7uPxuIM+Uz5vuuAhtS3LsAUY0CVHmyq9AYuw9Neu0/7nTs4zPe5XuH9duNfSZpm6xTVtlS4NXhTbG1ODHAE7idepIwgA51tGpp8aufyZGHVH6+zZIwcDbI8xNT9/2g/KiiXtE0b293+tBu5fOYoOTfRLgaRBg/uTnfKXysDmKeErXqixmf7ISxOWZZMZkQ8mikv7tuBlpPFvMnAXWmc0dwaa7jjmJ2HjZx+PqQioNYtdSupiTJWD5R/EBPo2DlJOAT7dQizV/Et02ju3oDgJf8uZowEPEOcWC4QTUGIRVgxVFjcFf+SiQRnhq2tEbE4zlCzwYmJEnC18dOPWAIoAMSqW4HyKPV/ZYiyMEyzNYsdrI37iUHNCpSMoHxpRuA9pTJ3HEljv6DQnOVHb6SpKe8JZpZ2ICt7HUj6tSoYh61IEo/Yn3xI3y2cQwyq2Oxm+O//GeW7l8m30ML3Df/XWx7bZoPlXl4HAVxFcF79+bqdj527aNb62CdYuhfoAPdhgTN1JP+s1bNYO0lOKw==
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-auth-credentials-external-secret
      namespace: mlflow
    type: Opaque
