---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-postgresql-credentials-external-secret
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgBTeult7ajVVGdqumD7RCEVHqui0s73/t3pD3lhrFn73OtaIJw52uQK+PQC07ThG0FTR4ztD4AxNQTBouRxxFpU4gmHNww0jzOfyGSWx/BEAHrwm7naEfHJyjPEit2lna0tvzZatVqbXT3YZPVfuQJtRBsQ1iS0VNUlD0QTrJQZtUgbqFjodtR18lHcwlzaI/jQRoB3pDlvotwfFhD0mqFsa/AOof+VZd1qCMDCaup/kz02WVhEwjcg/Jr2KtYm7zgoh/c0xdI1yDr7Lpfm2yOIw2rnnLY14SEjwdr5GRiPmd1wQo3+DDJEgKM+0kVYQK5ewp5WcHImmm7vQv2QQwHg457YNJcfKQ1YhMK7zcpzpwFw/eKuA4nbVDJ2zhB4RpekhhAoZdM4zgomlqfprp9hXPaYzIJ02N6VpVmmgX3/hQjxm12CzjXcIl48//54/Ba2pKNZh6zevwOJuCk4F6/HbMOv+yqtRUHMhlIc5h32ooSUsFs8/awh47voc6puI+BukvRxNqUyHeMQwB0eGk2uURvO/dmIQPB70H9Q3VhxeivDGfdOj2E8vcU5r2BbrTA67388UkEVd6+6ToFCFs3KXPx6YiYp1dvu9ZViLnRlmWEsOMmm8JkZKzNdIZxyqBPljKB9B4UpVEhYIVDmItGKrQRcTx/DWgeqm4OvozoEp2bHYzIkwQql+pWeFRqb3ntuPiyu40rkuwEKHhBy2iw=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-postgresql-credentials-external-secret
      namespace: mlflow
    type: Opaque
