---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-postgresql-credentials-external-secret
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgA2n0E4smnpFs4wMus86FL9FtJTSrl1Mf4ApBYvzeSPINeBcz+Qec97KzFiITrnSJ4VBqYyprMCkHm9iPmZD3RcQ2xjqVq/DvUvbuulRn8oDivbKWGqPzDcM7/v9xGWJg862M7TeLJBH54SM3Al/PjMYq1nfcT/cx23blmDye4BVxZmg2D2suznu0Iq4BvFlzjra1SI18zT4ya5VjjvPNRu/YUslyUg/+UmJfuKadM2DTcJyEAKQpJpb49R/EjhYVNBt4RrO01tt9fGUMRrFtLoamSaxdTuEqOdLMnUomS925wz2BOa1dtJV/8fg2+TA9aEPoqlYU9SuZ6RgMKtDECt7BQpqOKtEatit8i628gSgTEFXqSl1lCnxOAsYbjyL7VyA01NoDT5wj0ce/d4V57UrK02QMh2RP5ERBy2y83gmKnUwoAUKaDjFrpjiaHSf96FnKKtmHrHoipbAiELSSW/NXg0IBkNZk2E3cOPRomCrbNvDF1bFJ8KRj4UTU4z+B6did6keC0+Mk1GsBmcHZQ6TpmvV1Mly7Lsm7MoSbvK+VhgTraz1ob3aZ1owPQgVSYVEB6RqesEbuYoITH+lL/Ztoikt4KpCji8YO4SUJvBA5rDFILObsoUI1zeKD/RjBTb2C0q1nrqaYRwq8Jinbij5xRyLttURVEG0HCn4+RKwwUyhMAVaj6viLmO7YLLukweYZMy4h5i5nAcOZi87qY=
    username: AgAV/8V6doWAkj/nZ17jWhBwlrD1+gDX05Bkf1xcyGMknAOc2YTp2auKNXl9cCGmDLJ+a8sHw423QUS04NdlH8NQVPWhZhuUlt7sCy9Gxkv+ZLl12qqWFLpo4Rq4pzGtCljSQGfdicyZi8j/JnwFXfNj7bXBgiI49lZ81wAFXquCJ9VUuq1pfxfbMaH3Rf+jZzOjPFqih1FsYxR4PXG4wNQGwakz6oNtTrWxUWTZdKsMDItVI1IUjbXD99odxCEHEHVRh8bLIwxPfRD/6RlUdA+6to4eoxe4Gr7Sctf1kYRfwbU7WV/wHByLgEKMkdpBv18r6VJS4g1OCdeQdj2kPGPkHOftEYiuSzAqD/kuFO8q5MAt81EhvWAlyjVh+3QuQldUC409nrIKvRrahUuYJ1pMfe0FXEzs0nFaJsa1abBS7J9WbUkVrORjEzzAzRtC2YWLEnTGNUClnPAUzJatvncf9i/bRej4hW7FlJ4l2QVus4Odd6sO5kLB7UfdNPFXQuG3w9RfI6YWkXugBvqdLmhTGTPZQWQCrdFzsi3P3S8cdAgIJeqocy55iIWWljcbx3/kTW1MuxdDf48/3zszOJ5UIn8JDIWR3S29coPgVye3i/ObUGSGS2VTs8LynlxQePm7DI6wrp0I/KzGC1wqEhuN38AI6SxPNlFf+YtMtVc6Ssf3hsFDxU4BoDtErEZzvKa2dl0mznU=
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-postgresql-credentials-external-secret
      namespace: mlflow
    type: Opaque
