---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    password: AgAAHYf49nwfbvJzAYpdj1wVCJb6Oa4CSpLLf2kH7nqW8OLPuzWTtm1KJOVCs+YwlQhd2kH/mjrAj2D7isjyfw33JnxraDniCphmTZW+3Sk4ZZzkelKdft3YlI2CIaEkN9awgFlggMov++DWKexuv+65ZDx4tRaXXQngYkwD/7YcJ61EJCXiPoRSnZR9DIOdGWAHfKCwECMW0/eVfegirTYcq4DxlEhbCWNgn7yEBBnrq9/RCDf/V1anIiky+AtWKdC5E/XyAsOAQefHZ6IG9Xcv06195G0mMX6JkwnvrQBLILpVbT8QHFUcNcQ76/7n/AAkhMps1yw4BXfc/RPX+o+sJb8Lma2CEzjp4m95RbzrHl5P7uZdVAFvCsAi6OEPkYYa7teA+jatXH13ikmdush7tD7Cq23FWhm9pjjJsy4ywy8dCjc9s0KFbys3JnsSI3jwFRe9AhSJEYvo1KVcrUBuF1HpvQ5HbCn++IEVBE60BBXLYdYglQVVr0jrvhm6DBoWNBxXyV6mu8w9Ciq0B3fRzCs/xYbpGfkSe5oRslQ7MSKiE0P3UmNqHu1jQVhxdIlNWefM/WL8+IkMmyD5RRf4ezUQcEx9v001bdR6fthaStKsPdZoIb4/yJDGPxl8O9PH02kCQET3SQKfK8bm9aB38TZyIuNYS+sGfk1wPdji2E44nLswvhhkIlTDkTb6cC7RtzFxEsmCs76ST/6wz68=
    username: AgBBBl+A/DktpNDXsFYfkf7wf3HYvzbhnXzXgKX8jaN28YZX0v/5JJHcH9u3MqmRrdYZ6qiXW7TIoOLIUNi7LV4mN+LXopLyL1Re08+YymALMVUpm85Q1TWeXMaJ91azzxkd9B11TGTv8L3A8aP11v+8ijH7Fn4z8t982NXlmMYATXb2yIYpTK3/sEQa7o3cnRTNjQFdDJ534mP7xpqdpkF+TdQ6FtNfwbc5oi3ICzI6I+dzqjDThw+6JT6iAsvx5OWqBJh9JoO3cAX0WU0b16SxIAUQXCoJY2tRFoNtGCn9HcgB5ARlnBDo8G08vXNTjpFN+BoGuGkJf2+A7WJZAbQ4BniEoKB4p1fg1rY6tvaEttGAJX+U7GADtDBhad0aeXOZ9M0uJjbyrSpfskQBQ0Tb1XF27ChxIzQffCXbOeHy+RMlerxryWBQ8W2x4p6quQlsnZmazs3mFeeBQGmh7Wd/cQG1iOP6HkMKHdHg4zGr3xaJChQq/nT1H8ohIW1sq9fpD0ZDBQmuudM65RF7qkfKU/Fz4QXdE5FjmHVVfobJcyGZopO5r8QEzfB2FQbyg1Dj828mIKmmyey4G5cDelBZAqn5jV5KeqT36VtbN+03f2/L6e8ZJaF39kfycBXCzHEecUt9J3FEfuWvs+3aPBelsgciP/QHu9r13mw24zwbUcqIPMiCt53Ck+uZtoQU+UYzCNBYLA==
  template:
    metadata:
      name: mlflow-credentials-secret
      namespace: model-pipeline
    type: Opaque
