---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth-credentials-external-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgA/sOqB4llHpUVk5rSVdU85D3WMhHO9GkFdyHYhd6059uQSqc4ugxmsOPcSTC2zkD4GMYSjjTIio8sYz+BA758SaqAAbae6vt8MM5mpcEzCZm2YTR10b/SAKutjabIHlXypQqPdhMkW+WO0nYSXn6gLO90b/cKE5GwY5jWaN+7a+Jpv+pRDrCfU5ELD6c16uSIUjX+CIQv6Vol7hswh8PSXnWKjyPuVdOQZgL0KKhEOP8jwM4xxJH9gMjpFdMXRzrXpUf1DniYZCF6sEglzQO+LXxMxozqe5byJJAV8bkiOhcM5OFwFk3CNCAQRFXJFw9t7iKxR59wFkezFvcV+W3yAjhHtU+8uVr36hEzVXxgwkSz2vp3o+zwB6L25vbZ/odpX6RJGcoWabf8IJP+aSJQTQmV9NjMh/0yi04xZi0zyB9vrUI/EjCNc17Ta0Xk4FvHNh7DGz+sgbASmYRjvdObMgPSLRqW3O31gx7+Ly6OLTweXlak576o3WpuVoGhm9Q1/Q54PAoFT0+v4pNgzI+C8Bb3raf6192gsOkylS5lQ+DZKiNq6zWC6eHdQKDnvGHCiAKdHAhefxw78pZXEld7TiWf46YPuqyD2NqBfLhdzJoZdF1DnRuzVB/BH7UAGg13UZuqUz5Fk3QtQZoph0Vjw8un+7XWjsjXJJtF/G7KWCwB8jXvqakn1ucM52h7MLcFuP8JYKWk0cBlI/iKW+U4=
    username: AgCdh2Fx8PfpGH0zcS6jPJVkcFjvvDZ0i3mopIAAqdjSYxDTcKaxgguY42Dqi6CxRhCiCgdgm5sSX0TscikKK46fYxzhHcKqxqlq9/mKkbBSAvdLKyMMjLgq9o2jNEi3xQIf6e7c6mabHMgJGtAemqGruUXD4xqDLFPM4idX3ducGWUrVYWNoq9XXODEMcqFnjjmYpV1E/MxhVd+ukTTcLdCULedBtBVFyMB7MWhg3gxOsjx6z3BFZFMl9Z0Vi760ymI8wxn4XD/NKLT1MDQBknKkzMUWENYjwBOCTx0t5yuXscS1L4dKdMGgHhZPoDvI1Tg0Lm2S/9elzYRkF0z/wnHgyIbI7yP4mynpSzN7ODDq2tCH4z68hQTXhqZw68R6TIZzlx5q7QO0ltRHwc59kpwxnqL+cvJbhqfMkKZK/6toWz2SQOT7nKs+dQVbzRPKveDpDqaAnCBgzYRcWu62qPxddCGY4JoBksUIAYsLIBIQOqwb8+hN09CZu8iMl0KkhqfRpbD98aVFP3wX6HCrgvy3XS15Zoxxd4XyQIgGSccf53sLXh3I+SoMt5Puk8qXEKxLRJb4d61ld1CQyxQABNyJIs2wfyeAB60P+VD1P/JB/4dTg5vVzkRExmYd3XCZM27kIB/DwEYPEmk2fkvhX+5ed0qK5LilnZl548YICO2F30tQx32/qZfIsKf+EesoqwdRP1MJQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-auth-credentials-external-secret
      namespace: monitoring
    type: Opaque
