---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials-external-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBAAFpQgUpWUUy2r584rX0nM7APUB6Hw/FvSzT1Xvljr5ab8ql1LVcCaqtpOe9yRGrDdXzDUTzJTBvz5QyFNZTdUVDTUxzQZuJLALG5ee6AFphAj8hbHKmEdw3TR929MOTBVisDKfNZtcMfqtZxFYGpramgcaUHvps2DafXICuYfgfQWywA933hh9m4/JlOYMDJI+h+UBZ1u0tK+ih203LPUOxBOOtk9mR6qBRB0bbnabUItJdN6eNH0mp8vDcCmKLL9aFSTV/O7YYNGZnkxvhXf51OxQ3cFZSbvIf61uzuXALrTt6qEmecW4jTJiFM3cD1WlxAiFagCFqOeQn4b1cPngvd6IQJgpgAad3zYJCIySxhwNSHlZGbQLKWMhE6XQp7WyxnSRkWHXRxICMIY2i7I7rGdlhyR8gwYOe7yiGAtv8oyo/H5wrnFXrz2AOArb6d687M4GfhMcHrh+F0utqD5Nyq8IygRfZXxK04cUUu0GrkWegSbCkm8+OYpVnC28SjuNnsabhsbYUstVIIrWDCTYAVua/yuzaCtyiZ/dBwonWh4+jANPdvzW/7jUU5bmKZcyJGU6yaW94NyJSD0S/r6Rk7NcXNEPNWWgka/uSRXGeZI8GsUEV+UKOycHLSSa+yXsTfJybl5I2lEKJlD/fUjJnoK1YXMvMzzpeBAAH56Ri8Zjoay/0tZqCXWctghmp524nX1KA=
    MINIO_ROOT_USER: AgAw06FrsuRYVFvv4TdP5e0ebICDMAeL+UbKJuyFAms5HJPETojRa/oxj24NW1z4wH7bnH+RNDWAtTlLdAfJTRYbbnxYskxjTsSKG07zwfgHxiyuzSst4MKYFKkhyuAFOpL4ygh0AnKJDEYEjgSu3ux+1LAA3+yGkyiVwlxlDPYbA9hlLquEAtnf8bwj6hQzw8ShroqERlmaQSw3QElXbNjwVkGy+wpbbKinwbgIfA8En9Xw47ufvdogbivVIQOWg3Kxs/Iwdm9ET+G9PP4asLDtI/3JN1mGMnaIw/+cIsRA1TsuDIpzUoYsGChyoPQx8GdBxklvwkr0cI2LtFVY0g3QPlMNUWiyqXvUXbItI/ngExioeEfDKIShs+ZvlYbvoB/FDUifxBFWSwJVF8GXej/0Bvbn25szzi4UAJZLZ05vLfGUGG3GMreQWlHT6n4BmHO7KexypbrFrdO9yabKbjayzTxo4xWRx8Gjw7jLVfWJtlfet1o3uS1SNDqN8WP42LzO3BLtnW2s5zRG1RUwNXDpYP4Oz6hwdE18Nm8X93llJietEX8li7kN+XjxonxEDtzeHQMWe3jDk/kNyKv1OcnWBv7OT+Cp8u0iBmpszutVhUy4F6s/Rk1uv9hEr6yIqp+a+keKJRk37nod01aNjaM1IGiO2HTNFeQeu5dTDnCiPiaB1Fuq37cawyvCD+vRJcf4ovp3xA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials-external-secret
      namespace: minio
    type: Opaque
