---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials-external-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBj+riR8gGNO7NeOZqmdg58n/JXOGf12qwrTTyBY3o7MKtEbmy4/ZlxpflMTV2/51SouU1DC0SdnuaXBDz+aRoy5Yhk5zYAExvPdqaYmiQK0e4C+RIVX8cZ3NMw/9E5OnDSz1FxQLK7B4qAps2JmQ4lluYg9ofcYmQ1j9OaONuMVvoaqvRJbODW2H2iMLZWLDHhueRk2H5/FfOZrVSOevn4JqTHu+AAmyS91WnFTJYdDMBHDkN/1+HOP7V/LrghpS1dn/j5j1yNRWPFVEcQHb7gVavgUPzIWwhZFD3xRiv02UxjwigsqOwlPy0BOzFbXx/aFDkSCVRS5dlV1lrJkkAf1Uv+A859ds7qi0yJZNTrB24b9ayhpx7Tplfu7KU5adlVmkvO5r3t7y18ozydYYaYJ0LqvNGqj/UpYJGu4V1pbrXoBw8ot43YcuAEYdSLhOhk2HgKXwnBQRusv8wncLj7SiIyLPYdckdiohO4kxKf9dUaS3Yjsy8pceFz/L0nDamHHfFNkqb62ieUWw6pbGi4e5eq7RF+Dz96xmUzHDJQpf/TfaxBxDA59GES/9zdNOO4vWTfyTlPNfPk3mb4b2M+6Y94xQIBA9WoI737wOmYlQ6U0E24IRB5YA88qmZ0Bl58vKmiTqTvB6gSYghm6xmgbda9KHgjzd0qBYAGyOLdGjkOnUMTPErdP6YyCRd8qxGFw4l/egkf6x6E2xtmf+A=
    MINIO_ROOT_USER: AgAy1phRIv87GRev/L9gKIBGTsCNHNkWWajpghYuKemTIJq7w1+Hr61P9z8aWELtMhh033PpPSoxbbPbBz0WZzl2CYv4XFaY/S8NKnN2IiNYWf83TEsfv7083nF7TuH2v+bsyYaVIGv0mJkLArNcxFg2x8UARFSyPZM/725E31UTEB5x3S3op3gHnHdLb4dzLwktS1eLmzy6cg1F1fbonZdx98dbl8PwgGdwpG5O5hZpNCPvq6cMpdGSaPuo1s6JuHbW8qKvqQ73TA5yHIoRtnaLNEPZFWfpIAaf0HwykautBo6I9GkyvktWKqT6Idm71Lk362eUeOaOVnrotAcRsjPo+4XGANh0TCqzRiSdIKlMoBgZ8VusYQqlBtTn9lMLFPAV0vCIdW/2nJZwc/XhR2PjlFIAhkkBuGWVBIttcBh9i3NTyi8slGQ7N5G6Pl3t+38cKE8PRjqBUeKikNs2niMjwq6cnK+OluvREpkPxYzwABx3PsDLoJWa6APXjhjAup4tupAAbAocBFZnwSFQlZWzC+p2EHd/vM4FGAv4DSH0wXvhheRFzBqwrZxMaam7SORK9u6uICNTBg/n2J4A18iz/iZRDaB46vV7GHSrCLSYqtyI6bL7y4kuJ71rQUVjvSlOma4YG3R80aW8fh+t19j8yxitGhIzWJH1rmiHa/D0eLEAsPY2ySUsw7vmK8TM13JvE8az6Q==
  template:
    metadata:
      name: minio-credentials-external-secret
      namespace: minio
    type: Opaque
