---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials-external-secret-reference
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBXoU7kG3NINd6tF6kjprjS2SId1MhBNdAtqErkk+V7iFk2DJoSj70oyC5tdzzYhHL2WtnyvRVEY6QVaWKxeFGrWtT0+Cym4kKYjOz8WXjR+ttBoNdBp3H42QXKppxfcH4adpHxGydjxzHBUSJINkR4U/V21WLvLc4VcIWT8EyP8X4nv+VIG1vS9nQ4BXQflEbU2bEyTYnbPJutDqDmIxIZWms9VH/JapU4mGpODSIJyyFY3RVnzXBAAKhwWtWg6SkoXVSXSZ6oJInoA7afF75PQGvTWfeCRdZVqyBIQ8yqoACs5EdzC5ot/FCSq5IFAGm13VhHIHaLBywQHP4fBofyb2X/YD+nTsxRYArLHu0DCQ2TxrVtDQ/cPAR0oKnApycNtCp5i+a6Wfm46KWRGqJR4fRYup6bzOHpHhPst4LSx5Qj3xA22mYewnXsDkmq7aDaopGtKCQVF1NOgm5zZ1TdHm8UGk9WKXOEhCEs9GnpLZyVjhxdcRWyE5DRQn1bhLB+OeebT3AcJNeODC77ncGuhDWpQP2TFf7Y65yUudjyGMI+DqwgInu8ZUp12nVGgkC1O4obD9tzb+w20JshroyXMfHJ0El3PnIrVmYPRyGjjnjqSWiTxcW/IwbScGq2QoAvYU3AJz194BSBcXB1c05JRscN3gNDmUWF2jFLmfiK7HJgEH5ppSDNnb2AGWYdyCaENCIaSyFehrAE2IGm3eE=
    MINIO_ROOT_USER: AgBfdb4n2gAVl5LxSJ3OQR4NLI8volagKtUENcCoqo/8vVcIxPxzvToVczfHEw1YA3HJEQOYbYNVu1sN8jtgIIIl9EG31PUYI+vlDxFigE/G1V2sv+es/I3HpbYNfhomwwbkle/Z2XVnTXUz+Ah7W5FWMM9OKSiqcqGOmLH+UTehjPYU6feKwetfvJcge5CKFnmWXyni7w2cZficvjWQDU3Guszkjcyfhryon4qYhxG1CtnFhPZtKQl/DjaDi1kRMv4tWsRawDW2Cdjovgw3OUJQ5NV5xm0Eg4EYMrrVQLWV4H0zo5qvpoMdACXJjKpoMXxsSraWCM6TFfr1zd4vpSg7ybvg233EcFXR6EsPP8OfDmGQYt/KwyBTJqKYiy3hWit/a5Uj84nyefZd/oJpvHzXCmvNfsfLKwiHL9JP9P/t9bQrB7CaoHGZBVsAxKWgGucRCmhUM1vBuznKqUz4MACJ+wXOmh8RWV3NbMq2QiYbDbKMaoj1jQJoVF+a81tk03PVML84W5VLTPbjMwsSIqF+wGQSIw48z4w9igTi5IvXvhS3rvHd1aZlpWq2Ge5cLlVk+l04M3UUbsS80rFS4MSuHvR9Yx0ZPpgW18MF+1hJ3RiEkIq0/XdZopasUmLszCSaAt9CpXEOZDquV52HBJX+M7hlNrbnPlJN9+6e/CYrKcElXTITTfYvWv9v8TRQ8xX1M+TbYw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials-external-secret-reference
      namespace: minio
    type: Opaque
