---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials-external-secret
  namespace: model-pipeline
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBsktvd2YFBDt2FOMZr30LS9fyWL+HJmU0y+hhqygjOYGITY169O8l5fNw4gtm3Q7PvGRUPuzBERbgeFyhbKVfIP1yZglGochvvjVgMsh7qONhkkxdvNx6+kVIz1EyAOz78xJKvcdF6f74p7jYAGm2iw4e/T4+T4Z9p2oHOl8OvFgkC3LrfxbyFE1nXRmarEdCiaty173EbSFu+/tmFolIpT1mb4CSS6O4VEuACntK3xZVJN032ICAdY4VJmAroK1oHo3krLLKrhRG/i/c3/TOxT5LA/Y4ZwCdKqXKcOzNgAzYTZnUs5oCoED0w9B59bskuVMKPeAnvui5BLRxDM2XPgJgUonWkCEpKzMN+vkd73YdiANoYKR8BG4d3thcRg491T1iVPxql00knz1SaSck00MKKqq71jeLsaCWaq8Ckv8f5BPCXXEfXMp5SdwY3t1ZgHu9XjN6zB/gqkbUv5dHMZVqYbGTXfMUbC4DHBjCUsDHUo6uRqD+dWlYsiW204uqWB8ZJsjvSMj4nnZWP/gApZYMzK0K02Jh3YqNtem030fYpISZVFDRdFLESBhRYokUu4sm+cxEpLBV5VIyflMfZU1E2ojlK8a0ya9xsbpIn13aHGU2RGGFY7F5ezZOr2KoZHo+GTQKMhcVihjIGzO4GdhtSzcXdqmS+M1zbJQDa1AGTvd0AQpc9xUhZrDLgmEyDt+wK4poPbHAh48fGDEk=
    MINIO_ROOT_USER: AgB4X9jDST6Dc7Q/pU1DEBHBZENdEjfhJNSM0FDhdNK4ael9oS1Ich9Q6t9EonyI4jGLKCDckdE+xQ/zZw3/qCDwni+bLrBEdKkv0E+3fDtQHUK2Tux9NU/DDpi3j9Y36Hu74lzOg3tHpwdSFCG3tz4L/da2CRCV6JpKH4b6fWwsi+CmqyaXqnBEcnAv0NKB0paVoC0SpFxAZ1oOpUt9m3hOgkyt4Gah6TBwnZbGRQWgTYu5xyY7kqUn3K+gp/5ZLxLijqrycDifOiUeu42lV3658sJUsfaDa5GIKsWtAh85plzC7ZJWzxaCMg+4JqyzLiuyytFjBx7Kbn5RdGwmqI39/LMHaVGMOCRKsxKu/+GJPdv6IZox1oKprfkwCVrDgmr7La4lVkxGiz7rujDDEV++lwIokAZKlPiHn7SX5gnKvEYxzszUem0CP60HC4cskHWmmdn4cSHmzMhB6GTDntTt5SYQgZwpK6ILSFHmuhweSwB3/mzQdSjnfB3rLtbpAaw5SLIEjOUgNokWbT+W6oTkDnUidscUuUu6yihvXcyuzMU6tpNl0gWPteGGbmovZKvseM/tOC0PBQfRSDUOecrGKS2TKo8S8RNX6czFSQnPWIibqQvoO7JdQg95Dc88dVMRVvu9ImroJ3z2xjjSEvsHPs9PFGlJA/dLY91rp8bJmQuv2A9ztFD8ApjnRB76/Kbd+ccP+Q==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials-external-secret
      namespace: model-pipeline
    type: Opaque
