apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: model-pipeline
data:
  services.yaml: |
    services:
      sample-echo-microservice:
        url: http://sample-echo-microservice.sample-echo-microservice.svc.cluster.local
      model-train:
        url: http://model-train
      sensor-data-service:
        url: http://sensor-data
      machines-data:
        url: http://machines-data
