apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml
- rollout.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- horizontal_auto_scaler.yaml

images:
- name: icantkube/api-gateway
  newTag: v0.4
