---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: cloudflare-tunnel-ingress-controller
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    accountId: AgB2p0zqDYB8Xo4ULHkdUmw3kxBhvUcno4IqJwicDDv8Dco8dEaOI/VBauhQcQxH/emzEva7mATP9K/lXtgm8reS6UnVQyixQPrDnGmSk7WQ+f+fkUEZKU9+eqnj0go4H5woD0zuf9tIAjsIvSGYuTon7wVd+szdAUdzEr4q0DzpKluzMB9ISqJPD+6cwCly44hYi9AcpFsCqET/cKGHplnoPVS6elFcejIYiYDVXcoVeHXGBH5RbBU1yvEDTiwXwEImjq3URnRwHHh7K3KMkC/PqTHi+Llzc8fipHkDr0x9QhEQZ6jrrrtgaTsm7ygCVBvRZjlsLJDrpk6uGeWd4fvBaTY8gi0NaTXx6eOovvRzWcX1KnOubBy8kcNJwJlaSHZQDFl6fxq8Tkd+cK/GfTKR5yTNTWhp2T3yCuX4PeAOb6LNkw6/RYGyx6tJUEfRnBmXD8dm+mKkeqSTck6ixixw+e+Om+zUbcINnXefl/6M1s+dOYzIdbpuR0M7cBMUf02yMY3sHxMobMC5ZWU9qx7zg4Ehp6Gws4VhvvJPuuAqK+TDjP2py5Boom6AHu3cESZiBJOXc5GiFKLpq+xnyCti1r4eQLVQzHc60xocUht9GJYxbPGYfaJlL04q3sR+XrnnchtEDxUiH+NLEQXjCra5Za4o436vF93FjgQtsPsIO+vjcjy7KeYs7pLLEtq0ySzdvkkDTzA487QMR5xW1mkWchYYOC6v3OoEj+T9a7c2BQ==
    apiToken: AgCEQKxlkRaS/DwSTK4lGb95b4B1f9z7LRsO7M3IRcn3nBvPODrdWbkqS+Dseg2IvXKjxyyDmlbOiVv4cmlhgplXXnwq0FoQOgoSPVDsfOhYwSYIg+H3MFM8hZGNY0hY62T6Goga4MdOmUUMb4qEMSNqOfLUlKRxjd6P03mDtSGbicHpHDdBmukswO5AE9IE3H48DLumPQkA7RPA1RBtRbRyqyldP1m4eZ7GboOoiKmjfmLbmwbm+3MrkgHMEF/qXNLZXOZIljheQT2BXgqr3QhjOVZAaO7aEtpP4SFWxD5V764LxlO07gfIGb0FOyyYx0ri5vkiNIVO/z1gEwyBiEaZTpaXJAmp9lZhdbi7qSfPtSo4mTs9btPW/kZ0/fhrbKi7qbVE/9xm9QGjLK28zMg/QxWr2lK7PVivLVbN6JoqkJJnuRc6Eg/YOaoBv0rwHvhUIzH3hTKgtdSepoOBt8fzJNVsX6IRa30gF6ywQc36mQn3ZSL5erB7uQFS4OQPNdhOdApj4lV+DSGE9AOqF8DrL9IkmRpeMyj2tp//dnBz7c2rskyOaaCaHIlUAoPEsejsQctNw7fkXmQSN1Vittvt77gJTZfhdmEb24REEQIEnvH85UOYekaDccDOyZ1f3Votnf3VBvBtOErckVdCQHJhMWO1VJvyLAP86ZX1QImCYwl+rQZIjkdMvn+nOGwVsAOKT4bhj8MQxxVyZCVc4ezjTThFw8zD8Bzjg0ZUyjhmQnuFWbC0rCcD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: cloudflare-tunnel-ingress-controller
    type: Opaque
