---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials-external-secret
  namespace: model-pipeline
spec:
  encryptedData:
    password: AgCbnqrDKkDg3qPj3X4FKrMXUDK4x7L5PHkcZbJtc+q6L6kyGm7AtOz7K2h3Ph7XJlNTPcyTu6/OcfadL3x/D9eL5bb1Ikju9o4a4N/HMSvlauTbxdv5XA7OFVc+D3BTnD/mYh7YANTQgKMgG1WpMAivvlQgGxj2phk01I9Lbcj/DMLljGLvKKj3q1cMlaX92e59eU6lxwhfpv1J1tKl5ux7q1ofF2NaqJqoAlY9GBg0BPAFkm7wpp3rWSdDiDH9oelU4KRlUEa55HPb/WSRxVde/UJBlzdI/qgo9wolldRBRa0f1+MK4c/jhoGQLrs6MtXm5h7U1jE9BGwyc814z+chgk64lI734VKGd3fXatbW85t1za2uUA6viQh361LOyxqvF0BVfcgYC0JKWUKL4CHze0HE7M8Ss0dCfUOOtH+YwWKWGyrILXXiPZJrvCd9AdO1RHkiuhuwqdwpaeAtqQitXqt1bOvO1THoy+1elXK36W4XtFEHUPGtME/d1ELy4CBIKnXEscgt1ToYOoSmK7zwBkHhhfTaKvRRYLvh10ed1GmyDsoAUzSgjgm+zi9OCEv0F25+oDIs7R5gMWy7cUgNWB0OuXAZGCWzC6HeAGCoI/FJG8+KWRTI0ynuju2Kb4L8S72iVo/rSBam2Ru7ItKIQROp03rOJPmXH3AkjgiZcphTxt70rKgMr2lWL8HYltrvr7GMVtt/wtVmGhnAUN4=
  template:
    metadata:
      name: mariadb-credentials-external-secret
      namespace: model-pipeline
    type: Opaque
