apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: argocd
spec:
  project: default

  sources:
    # cloudflare-tunnel-ingress-controller Helm chart source
    # https://github.com/STRRL/cloudflare-tunnel-ingress-controller
    - repoURL: https://helm.strrl.dev
      chart: cloudflare-tunnel-ingress-controller
      targetRevision: "0.0.21"
      helm:
        valueFiles:
          - $values/kubernetes/apps/cloudflare-tunnel-ingress-controller/helm/values.yaml

    # icantkube repo containing values-override.yaml
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: kubernetes/apps/cloudflare-tunnel-ingress-controller/

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-ingress-controller

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
