apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-test
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/HigherGround189/icantkube.git
      chart: frontend-test
      targetRevision: main
      path: kubernetes/apps/frontend-test

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
