apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-server
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HigherGround189/icantkube.git
    targetRevision: main
    path: kubernetes/apps/frontend-server

  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-server

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
