apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HigherGround189/icantkube.git
    chart: frontend-test
    targetRevision: main
    path: kubernetes/apps/frontend-test

  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
