apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machines
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HigherGround189/icantkube.git
    targetRevision: main
    path: kubernetes/apps/machines
    # Eg: kubernetes/apps/frontend-test

  destination:
    server: https://kubernetes.default.svc
    namespace: machines

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
