apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default

  sources:
    # Postgresql Helm chart source
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql 
      targetRevision: "18.2.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/mlflow/helm/mlflow-postgresql-values-override.yaml
          #Eg: - $values/kubernetes/apps/sealed-secrets/values-override.yaml

    # Mlflow Helm chart source
    - repoURL: https://community-charts.github.io/helm-charts
      chart: mlflow 
      targetRevision: "1.8.1"
      helm:
        valueFiles:
          - $values/kubernetes/apps/mlflow/helm/mlflow-values-override.yaml

    # Git Repo containing values.yaml
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: kubernetes/apps/mlflow/
      
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true