apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-test
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: kubernetes/apps/mlflow-test

    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql 
      targetRevision: "18.2.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/mlflow/helm/mlflow-postgresql-values-override.yaml

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: kubernetes/apps/mlflow-test

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
