apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default

  sources:
    # Postgresql Helm chart source
    # https://artifacthub.io/packages/helm/bitnami/postgresql
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql 
      targetRevision: "18.2.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/mlflow/helm/mlflow-postgresql-values-override.yaml
          #Eg: - $values/kubernetes/apps/sealed-secrets/values-override.yaml

    - repoURL: oci://registry-1.docker.io/cloudpirates
      chart: minio
      targetRevision: "0.8.2"
      helm:
        valueFiles:
          - $values/kubernetes/apps/mlflow/mlflow-minio-values-override.yaml

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: kubernetes/apps/mlflow

    # Git Repo containing values.yaml
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true