apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgresql
  namespace: argocd
spec:
  project: default

  sources:
    # App Helm chart source
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql 
      targetRevision: "18.2.0"
      helm:
        valueFiles:
          - $values/kubernetes/apps/mlflow/mlflow-postgresql-values-override.yaml
          #Eg: - $values/kubernetes/apps/sealed-secrets/values-override.yaml

    # Git Repo containing values.yaml
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: $values/kubernetes/apps/mlflow/
      directory:
        include: 'mlflow-postgresql-credentials.sealed.yaml'


  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true