apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-train
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HigherGround189/icantkube.git
    targetRevision: main
    path: kubernetes/apps/model-train

  destination:
    server: https://kubernetes.default.svc
    namespace: model-train

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
