apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-test
  namespace: argocd
spec:
  project: default

  sources:
    # Source: Kubernetes manifests for the frontend
    - repoURL: https://github.com/HigherGround189/icantkube.git
      targetRevision: main
      path: create-apps/frontend-test

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
