apiVersion: argoproj.io/v1alpha1               
kind: Rollout
metadata:
  name: machines-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machines
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: machines-deployment
    scaleDown: onsuccess
  strategy:
    canary:
      steps:
        - setWeight: 80
        - pause: {duration: 10s}
