apiVersion: v1
kind: Service
metadata:
  name: kubebox
  labels:
    template: kubebox
  namespace: kubebox
spec:
  ports:
    - name: kubebox
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: kubebox