grafana:
  namespace: monitoring
  enabled: true
  admin:
    existingSecret: grafana-auth-credentials-external-secret
    userKey: username
    passwordKey: password
  ingress:
    ingressClassName: "cloudflare-tunnel"
    enabled: true
    hosts: ["grafana.icantkube.help"]
    path: /
  
  persistence:
    enabled: true
    type: sts
    storageClassName: "openebs-hostpath"
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  namespace: monitoring
  enabled: true
  ingress:
    ingressClassName: "cloudflare-tunnel"
    enabled: true
    hosts: ["prometheus.icantkube.help"]
    path: /

  prometheusSpec:
    retention: 7d
    volumeClaimTemplate:
       spec:
         storageClassName: openebs-hostpath
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 30Gi
         selector: {}

alertmanager:
  enabled: false