grafana:
  namespace: monitoring
  enabled: true

  admin:
    existingSecret: grafana-auth-credentials-external-secret
    userKey: username
    passwordKey: password

  ingress:
    ingressClassName: "cloudflare-tunnel"
    enabled: true
    hosts: ["grafana.icantkube.help"]
    path: /

  defaultDashboardsTimezone: "Asia/Singapore"

  persistence:
    enabled: true
    type: sts
    storageClassName: "openebs-hostpath"
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  namespace: monitoring
  enabled: true

  ingress:
    ingressClassName: "cloudflare-tunnel"
    enabled: true
    hosts: ["prometheus.icantkube.help"]
    path: /

  prometheusSpec:
    retention: 7d

    secrets:
    - etcd-secrets
    
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
          selector: {}

kubeEtcd:
  enabled: true
  endpoints: 
    - 98.94.203.156
  service:
    enabled: true
    port: 2379
    targetPort: 2379
  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    serverName: localhost
    caFile: /etc/prometheus/secrets/etcd-secrets/etcd-ca.crt
    certFile: /etc/prometheus/secrets/etcd-secrets/etcd-client.crt
    keyFile: /etc/prometheus/secrets/etcd-secrets/etcd-client-key.key

alertmanager:
  enabled: false