auth:
  enabled: true
  database: machines
  username: admin
  existingSecret: mariadb-credentials-secret
  secretKeys:
    rootPasswordKey: password
    userPasswordKey: password

persistence:
  enabled: true
  size: 4Gi