apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - rollout.yaml
  - horizontal_auto_scaler.yaml

images:
  - name: icantkube/machines-data
    newTag: v0.1
