apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-secrets-writer
  namespace: monitoring
  annotations:
    argocd.argoproj.io/hook: PreSync 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-secrets-writer
subjects:
- kind: ServiceAccount
  name: etcd-secrets-writer