{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-auth-credentials-external-secret",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-auth-credentials-external-secret",
        "namespace": "monitoring",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "password": "AgANamXx41Wft2CLi1D0Zo+MnLrtJHvgBWFrGCkJ/+PH8+lne2Ff0fzGJzSplbzYfbSUkTzGUBQUuMeI4zk9Z6ewyvglY7L+k3KOfMfo5abbZu+KnXk5V8L4E0w/BnH4PUIKEz+pODu9xejuyu++6LZs4ja3qKgwFvdUc6GcjhCJEKEZMR6dirIVBS9vCWrvICLo3zqhz0io7Hxn+oQorQ3fkymt8N3hUeOTowZENKRMeTxcMjZy7jmNta1Nuk7F4SknZ1eDqgLIFdJB2w0lL5M3gFUToM3MzpgFaw0vBmy3z39et8gqWe3c4tTryhMFcAJIpL7XNlkvPogINRqK8jzZMUCI1QsY787qzSapVV6epMnBCFEH6EuGAMdkAhcKfENgU9NGup8QiZmZJ0A2wzNR8JH8Qe+CsEVCIQXg4NOrBuhN3ViLG54EgpaQYVVq+gZdBJfetu9QYM1baMgdLR3LLOcN+gARMM45OwGyqPT1KPl2blYqkushP9Q0tCopn4KJabvm3B55dAdSxuEB7SbYXzfKe0lFelDkhGNIzNuTdgIvrga6Z8QMygorxUOLEI4dHzriaRcMYMOxS95YI2HIb0t4PZUGW6dTMVuxurGUaPi6bo1mUbW/W4dpGSz6fOsSG9koCQV3571TnGXfbPRInF6bXRkRKgC+N8ksSy4jRnD6siK8tHt4xjUxh62DJvcW+VeRzKsVpSGkkdxj5RM=",
      "username": "AgCf+8WKoId89KZkqPe1aW+QJjmF3iTUXykKi6V+J+6VJ8arK/E2WD/iuqPrD9LF8LgUTVgmL0hVVxBIr9zZ4Q0hV6vWeeXLzqua4DURs7Anat7uDZQaEmGt4Qfjf3fqsgBDwl8JVA37yG0eYdTOSVlpOPZNtoOCa5ytChxJmafHPwJpCw5OgT6lGcvEXgFQnNGt1Hi+Wpt9aH7w+lleKF0nTv5it3U5TgUTd6ah8cI44lN1/M/HBf1A4tWmWYj/Lltn+H+jN0RBaPnmA9rtSbV+STNiJVPygEbVWMmnlxHUYxoh9rw8i1kfjird54djZI2ISieqzKiUoychCQ8u7+MzVkulisQWeKckFE7GP8HiTQ5oiD8cgyKl2p03JY2cki8cC4rxiSElHqKG+i5Z27EH8mydL1EMOsJecrSwmsv5sRLJvxuDp/ymST5LglUVFg4Ic4pBThw39pmKSe89+nscvVowcygQniO3FZ3QFSSYOgDm5vPRclFKF2gXXvHP2EDEBTKeyYhceRunOs+IZDocI3sYQ+u9k0lcCnJ6+fS4C5rrv/hHB0c0ecDfHwmICoAIAHportwvK+q8B55itUnQYI8Oz73q9sx8XQpmQgkQhw/GHEkerbwru6KY8qOndD35nUn3ZY5R8QITUQnZNRbALShPZ/j8AbHhexHX2Ya4GMlyzubpI62oxK5CPD4z6h1kjxxbXA=="
    }
  }
}
