apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-data-deployment
  namespace: sensor-data
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sensor-data
  template:
    metadata:
      labels:
        app: sensor-data
    spec:
      containers:
        - name: sensor-data
          image: icantkube/sensor-data:v0.1
          ports:
            - containerPort: 80