apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inference-gateway
  namespace: inference
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: home.icantkube.help
      http:
        paths:
          - path: /inference
            pathType: Prefix
            backend:
              service:
                name: inference-gateway
                port:
                  number: 80