apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- namespace.yaml
- role.yaml
- rolebinding.yaml
- rollout.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: icantkube/inference-gateway
  newTag: v0.4
