apiVersion: v1
kind: Secret
metadata:
  name: mlflow-auth-credentials-external-secret-reference
  namespace: inference
type: Opaque
stringData:
  MLFLOW_TRACKING_USERNAME: xxx
  MLFLOW_TRACKING_PASSWORD: xxx
