apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inference-gateway-role
  namespace: inference-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: 
    - "apps"
  resources: 
    - "deployment"
  verbs: 
    - "get"
    - "list"
    - "create"
    - "delete"
