apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inference-gateway-rolebinding
  namespace: inference
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
- kind: ServiceAccount
  name: inference-gateway-serviceaccount
  namespace: inference
roleRef:
  kind: Role
  name: inference-gateway-role
