apiVersion: argoproj.io/v1alpha1               
kind: Rollout
metadata:
  name: inference-gateway-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-gateway
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: inference-gateway
    scaleDown: onsuccess
  strategy:
    canary:
      steps:
        - setWeight: 80
        - pause: {duration: 10s}
