apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  DB_USER:
    admin
  DB_HOST:
    mariadb
  DB_NAME:
    machines