---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials-external-secret
  namespace: mariadb
spec:
  encryptedData:
    password: AgB/5xfEveMPg5vP8TSr8w/S4X8P3iRuJ7Xk+N68NFpx6IPoK6xS6CMkwbPZLsDqGJRie11yH5dK2yQrG6FBUZFEC5PEW9mGNp7gawxVGH6+JiHmwc2VY55Bh50XZarrFT/uwo82jucDiHqbDIJjNCV50eudv2W/8WeNU7IAtNv8yNUaIYiu1eomBsgMGh3OACLJaXWUaWm7Jew/hHrzB6zeQyqL72Nk41bJFkhnrUKJKdvXm4z7+reLl6z8jRRWkBH0uEbDj9YJ2jLjDgH87VtYcB3NpFxXQu+PIdNqccVx8nT38qWDfRNIbdPd9S0SZW6Z74ZNf7TZhXErZHrpu4CAN6Mp7iDpdt/fb06lERTBg7qgagLHz6UcRK0HS5HG73ioCzfQIttRTMo9wJeQ72LJkLsjy/AOg/8PPSn2igOeyao4vL1ess3eSzI4VEMRKtf5AEvhvLQI6OqngIlKWL0Z71P+Zg8APkDqg4864+Lee6/W0zpnuR7baUS33HZa7Ynf1hTEfnSApReAd9D72VyCcu39DEWLEXBaMPWxBdHCPqBfK4Lu4qCH0Xsq/XKAFONFjdcyOLttrp4ORJ91avUxslAKALKIR9uqhj2P1XRO/4mBGMEVDJJMDPheIm996jlN63Djz8+dlwxR8E4J3QSwpcQkwafE1ASBkQ+3UDu9weBzySiCHF5zpp4dvDLjqwNdfJmw5HEAvClRokmB+YU=
    username: AgCWOze28DGYYoqUBgw5xaILEQBd1zEPgZSsTLRsP5krJj+UIn5E19foDFf+1gP6J73N8Yc8X3+Z97NsTqsY/3GslS83p92Ga46dGVlagb9+PevLeCLZI9p8MBrzLPbR6S35eMZKmFF6+NXyJHqnzG8+dwXyeKDJpuZ487CO4oXSqp/TIrp7k8+JiDLwRAiZ+wJK9REf7ggNBLFF08Xd+qMr6/vR9US7saBVVc/ED+ChQVlrm8WDlzbwScQpg1ELWYw4sMtwo0CMU21qf+Ku9cMscDMWye/unFOgeDaBvltEQYK/YllWi6q1KwXCxvZFMxMzqE9F0oGcLrnLE2V0ns2FETJjrj3/lSV65bCXf2rk9QUyK5d1Hlj4k4zoTGRJC7NjZnSAA716b3Y+7W5Aq2vZW101c5TF02d3YUs42iK8W8LsECwF5dj/iJoHyKPuQ+I/XkTNX5FZetoeP1QbXkUQLgYHvA5c6f0h0H+irVNnjvooABmp1FsFIJ/vzQMokqtWUpzfj+wMsV1IJMW7G89H9FzYqxD9AwVQ6ijazHkIZ4cetITE0YHJgYTnIXIHFoxzKyGNW67AXpXkhamOmjsS9tzsbw8K6maSwO1MoqgD5E8bLODEWrRXdPNhhDIxnIiPZcY9p3WNqLQLWdeuBg91EXrA8ZwBtnOJZhuKzCsCKVPloQ5Y3WKYr9ebuPb3g2ode2yNFQ==
  template:
    metadata:
      name: mariadb-credentials-external-secret
      namespace: mariadb
    type: Opaque
