apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  namespaceSelector:
    matchNames:
    - cadvisor
  endpoints:
  - port: http
    interval: 30s
