apiVersion: v1
kind: Secret
metadata:
  name: icantkube-repo-reference
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: xxx
  password: xxx
  username: xxx