apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- role.yaml
- rolebinding.yaml
- rollout.yaml
- service.yaml
- serviceaccount.yaml
- config.yaml
- horizontal_auto_scaler.yaml

images:
- name: icantkube/inference-gateway
  newTag: v0.47
- name: icantkube/model-inference-server
  newTag: v0.39
