apiVersion: v1
kind: Secret
metadata:
  name: mlflow-test-flask-server-secret-key
  namespace: mlflow-test
  labels:
    app: mlflow-test
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  MLFLOW_FLASK_SERVER_SECRET_KEY: "ZTc2MTA5ODM4NTkyMTczMzEwMDRhMjlmZThmMjA1ZGY="