---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-test-postgresql-credentials-external-secret
  namespace: mlflow-test
spec:
  encryptedData:
    password: AgA7J/ZWu3lwgEhXnxzxf0dnp+B/tSIEPx3GkfUhtWQR0h+KlywCjajIptnUXp6wqNiQn72IlreTTiUrSyYDVsgUQI1Tofe/zqGohIhXbad8Oz7tm8LqUTvjd5R4SfS3iXYmsWPOs217AzwEi3EO+FRSMpeOYq2tNVVcxirAW9Fg8h2GwlcYSSR5pGP08q8Z93DOhd1NMuShgMAcuZUg7DX8f9krytWDe5FL0+jmjRxXtMcJW/+Jb/aVuyYYCVMMh7LEgD1GDmryrO02/RFe56xLzJFdVx/aA7xf4Wle+0hO1Jg/AVUTWhupd3N4HelZxXNkAmwUb4/i/UpYQzACbXxwfMmLDdjBG7pwXrRcYvLSB5V3v20H4n33S9A2+9oDYq6ZO39vL85aFi4FzDo9TpVxGL0F6R0MOZJV0884d5UQqdxj4oG585H0+47t5ENX6zIUNmz5Loeqg27EYW3kTuoOBvEYGn/rJN0MseJUl76wxBv+h8MXJTu7RLKy0S69m9u5Dvu4StNTtAO65Yj7j0nJYjzb7z49wKmMXt3xkan4mhVPHK8syVQ0pxdFv9TXbWipyIAEEtruAl4laK/LcP6MxrXO+9OnSNyxcqsOP93El8KB2q9ABpGRU/xEmy0OzQShXmZVgWweb0Dy6Yhnc1on+3pKeHXu/4h4rs1v61F8uqge209Eds9vEymRkMBg3eso243N4LKsA/k/EwPWhLA=
    username: AgAwNcbl/qviVPYKCaV83bo1he/8DaEfW1HIiV3Hy/5b0eHSUd75dyjW0DNJpImraDYOFJFeP66P/tfMXJeW7JcAl5t3yrJ92pAQVJZvx1CX6v5upbh24NYQFqmtCt3qHUt9PTxZ3WFrt3ku1w7QTDVaAwfv8eaoQbRtJBhgg+04VWnea1l73dmVK0X3gVew9z3/TY7FWmb1JlI/2Jb0QuE7IJdLJTgopKVM2I3rYFKLnhzo6lbWMLVXk5jtW6TWqcMgw59TaGJYIxIehOuVXnfpI04cUiYRv0uib5iyAv7WzLYWE+5Y/SfNcFR7PZZN0fUsX7Sya2qwCHmHkJNr/aSp80VTsFpRVj/QYijsQpRybKoERoDeJB1do198TqW2ZnkvLWtOuzmVN8BocmsvuI2sUL+9dL+MLRisZLRe08lxWUOljlZVjsx8AsU95PmAy5appdYFMaw2hoMz2EPCVTmspPZ6p4qpXHpwGI74hhupLOwnX6ZZ+5nChoYkIRdODnrYlSWlrxxcWHvdjVMEWrZ6F/22S+zX4518RvuLLKGsu66gEz7+yazx/I+jZmnKLOSRHLIgWvU3itzOcW32glgoqkTqihY+K1lOWSbweb1u/OUE0cqCSdTn4JiKdEGS3fdf35hFvAfNurhguaeOQ+gnaYk8d2BljVasR6YNRmauB9RDcgVAYLNl/A7Y6Qa6D17Kj4jKuQ==
  template:
    metadata:
      name: mlflow-test-postgresql-credentials-external-secret
      namespace: mlflow-test
    type: Opaque
