---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-test-auth-credentials-external-secret
  namespace: mlflow-test
spec:
  encryptedData:
    password: AgCn/gwxt9bCdAQ+GG5/oVwzeD690zgYJZ6c7HtLWQYWNyoF/j2E2kUFNA4adgKg9Zg5NmLH7p9qF7aAKAUlRznMG/ZG/C4JaEYDtjTN1c/KQgKF/nYmCn3HR7fa4oifX9WyKNA7FUdGeokUazP3TrhjmPUEyd/JvZZ7AQMTNyX7//pnyAEVdfIWCq/3OHSwNEPUmdiGcm1ci3HtTXOcwG4rfoEFlOpzlZ4lXHdXqb/H6vVPv1QlNFgPagwsDU0DU82cxarT0UiExLFrNToNF9ARPmqmYGyROku9Taijn18+obK5jvuKq0yiJ1kF6PUl1YdfGqaF+XRd1eqm/sIURVioEU2H64wmeKygzMBINqW/K+2jk/KRntUKqpkt67tKlLaI50C5tXwx064MXcdWf4LlsMxgaxmOvBTfaRVJ+rE0Y8MWloiqGAOPrtFrwjrGbjnyTrK4goZxv0mlepC7ngQG+J9CtRg4jNzQeeT1u45nXkDrhkYXlwD+oVkUxclRw038+WUdhdWleyD60B0qjiiqgNH90hlyom8sZe3bTTwvUezgDLEOdZReFLwIG/ZUkDIyxuu0ezBrQlhIY+KZoz1+0UxH2RTgpL3ela7yMxQJqIjUoyoxA+sIy0jCh9MgA84iZoLGxUnIRQIA+yTDZcr8ox+kmbCv45sBOexOFwqaIPDt8x04/f0Qo2DPyR27BEtITWsy+x9PjFuCUcs7r1o=
    username: AgCkgLLII1VlctIqn1ygKosuyepIV0CMByQLwEHYec9PV7u4JnJtPz9zpW7FwSpqBZW6/5W/GbT/Ikd/Un8E29lUItdNv0yNq3KRMHVgDbAXEEXaPbQuVqxcIXrGG8zDczCPSHAIj+iKIOurL1RgxOZ6gx2zUXLsjT4N5dr1mL5Qj1XJtXP5ts1NLhPh2g933xX/5050rP8x9gjgIxBEf7VuXpJT64YqKnDr5McjVGifmd8VzUFnIRyFs7MvP/BKUXwwufnRshkUoe1xKv1RVCyoo2hLnN8P2VhwH7NRbzH0L1GG9y9FO277qQbnR/NLH5wVH2c2QaQrzn/Al9sc9YSxcGOJpZOjRTWf3WvxuLuO8Jx7hMFG0U5HhtxMvKhLy3FyFksvxhM0/quzXcW2YTNpsuEbJURwG73BxdM22hONcuVRK1yhn+pYE9Z7w6ru/tMSx9Sr+zXa5Rh0MpUrRtrdHrYCCs5rbwi+Hk7kVof7M0BXwWWzTHnf3ivqMvGM3y7fJ4FMThmPTQFQgE9Ax5Ubgpm7hxp4LFRtwBOxEshM10L8YN++KDcSxhe2kKNW9favKQVqwIZ49f9V8fodC+RgXShqMrdJOfudiKZA/OvONx7uQtiFs4l59ujz8mq5ldQML9c6/mJIU7eAuDG33VrYDnuRmxKohYzLAoHPbBE6r5+lBwDn/Z5s47032xCVR1Ch9EXK1Q==
  template:
    metadata:
      name: mlflow-test-auth-credentials-external-secret
      namespace: mlflow-test
    type: Opaque
