---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    MARIADB_ROOT_PASSWORD: AgBUqy3VV2/9rD2WTBeDd2JpgKPx8UH2Un2UzVnJPynm1IoQyOrXzULVdd5IkCfXe3ImiDqAR6d6AzS5Hhkzh/V5yozjpGDcb2nOAIumksPwDidZ3PsZJd0gB7QvzM4JTFX+4GQcuRSNJLfLVx7oAfiBstNw5gls+iTpH1zeExmziIPPnoWykGTssM0jTjtDjjYx+oekOc9mJAdKQMWk2DTPe0nHvxRJMIVE1exqSg/mBWTd9swmLEvrayMYNTNoi8at3o8Gq8eb2gK1XnngeUryfnTB6TJNo6n6/P7u5QzEcAFSN+bK/1WdBXck6pJpDeHlu9/2BCIb3KGgQjTP6WtrirccfphvkjxZGX+oR23WwoGMoRAhtk8JrM19FOfhxn+D/tu8ODvAhoxQm6/8hUIypDPxlLhTpFBR7JUGb1SVh16MIoNX7wZU+1VWF7//cOT6gpfkEEY1jpn+ow372+LVtALZvYhbMQ5fFLkxq3kKv4p+ezix6W4YTmZ946IqY8Hpd6DkVSjw5Jii9SVZ++gMVeb001vm3ZadFVYMoqiLshfnk5aexK6V9Jk7QBXeCcw42TXEHpa87NgUwgo5rFqulEDMRPeIumXWRTCBuvyu1Eu4KNJ1Ne8X7FAtwDGqOLouh5OYRGBZVL8oJwD0ISkLyLpkpus77+JD+Hdcyp8cFmO11m7hmTXd4pAe1HusfvKC93pSGW0unjQqTtfwiX4=
  template:
    metadata:
      name: mariadb-credentials-secret
      namespace: model-pipeline
    type: Opaque
