---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    MARIADB_ROOT_PASSWORD: AgAeYEEVGlkOPorgKpBqO0q0+cyWZsasob2K9fZci5j/AaLAQxbpDUV6j+YnyugmCPSCTI2xtVay4pCwyF90Qljqkcp6DjaRDDW52VRxAuJIoq89VBsoqsorRxo2toGP3+h2MJA1aFLwHBz6/qqNebz/WV9zXKHH7hobLgSOTMInTiQme0v1/ayGNuwC7kr6Z5eEe49k9F/A5CE5svchVTA9r6blY7p2kwdmMKN25QiTxW2cmJ2COiX72jQqryEPTVZWvA6uRCcw3NujyDysuPV9vYrUKZMOJbB/gSDFExOjujaknApwbzx+yvoZqzdPjSdtlcn1scZg/q5IuDwPo+zhL8K8VsbZxC432G8nlg5ZH5x53JxOcUV849c46GGQH5SAB2xwtQRqQGxQLX1OjrLuqW+/GolklJhHtIWfTcYSn7OACzfhkecVs9H0g8W/ZPHFsIoYgYMjThAbhII2+zSXqsT4IMlkFfO8s9tDYH+UTwcqvKpahCSer2rLunhGOSHnRbvy5uIkChh5HiuwVPro+kBi1g1i5WkzLeQGjNCCbVkKZxK0Y80c6ZjxkA8cVlbe6Qj8ztBod+AwhzjFnEZog4mcpxpzmo2tBnfcrkNfdpKcDQhvJfhbFX37X7OjRWiKeHBRrr2vdPxp0QvdQPjHEVjFcruG1mwtKG1lFUS/OeXLBkrnJFG/+nkmd0ZSO11lORa4nlVDO4+BDNcESPU=
  template:
    metadata:
      name: mariadb-credentials-secret
      namespace: model-pipeline
    type: Opaque
