---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-postgresql-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    password: AgB7lOd8ho6rsnyhDF910hES6IBA/uQmvdNBP4Nk/V+60Ruu3u4rs0uCd1oTlhyhAyDKTyi5f81VeGsu0t36wbUB6ItZI3EwRGLnfuW/lmiiQbZfVNdb3SvQyyuMFXwcqQFwJJVqytEE/F5GdtlMuEV6Kf3JQVUbFmWrzLTN0OaG3F/4dcQLDSxIHpv+Gp5JE4MxU5uqHvbHT3UvgS3aTtE2JV4wIj4JHUB80Qh51Y1LM9HjMVb6FqKb2knlwdXG4jGlA9ZzLsPwOExhsahI+OvStKoe6tgt3x459F8ADEDHGx7yUxbnDLlwdlwN7AaRcOhbIs0Xp3DPbHRLj5YuIA9NTuSx4zKIdhShKKHubq17NEWyC1h/Bupdej01SDtYBd8JucAIVS74HSZNRGyGWSbhTk2+vnB9KHiCLpJWt00xHreRnnfSpkCiY9Pk1DZbibCKdE7AYph2qzzIsa+kqN82UpJQyNSvrEAdxOi7uPjutGb4H3nXuM+imcWqN/y2XmrnM4Abk2fjlTzZUVKKGrqcnDqZmv1sBWWN6eb31342u/MNvijPrAUr4MkpZyS6AtbzccxLoMsleMJe5LfLpZkljDdHeE8NWcdIlFa+TVbBKIXtAa7X48ShyQKCCJ+AqS0XG2Wc51u9Yxec9q+WdzvX6lLWcGMF2a1by6i+gk7GFBUqLJkav0fv2PgcN4BIxN0PE9eaFkrqYFd2tcgcuAQ=
    username: AgAeAxdOanJ1ZgO7N3PgzvGIDWVzjS5uL25VnCovrEnj09NTcTwOk+s3BenTGkgyzY04bwpFhmiXXRpsTuwjugI7s61pQ6p94o5cH5PaOPAFjknwsB09wc0i0Y1+GEkQCNHehMuI4gBhhbjEWN+JVTheej+MrmkWVG645YGAeFO1pSxPrINKNqqSLwx3V1nQJO9w0G9P4v5Delx8w2k823J2DaRkgL4DgoTpTX4Rr1Ao5wduJxtnx7nHYHsV8o5wH7QZ1ND4emqL+WBxuxjtqHc0S1uWW5Ht12bu5WLb12cacf3cCExIe/5B7DSEPI+Gz6IIFO9WGcyyVthQMl+oTLlDtFhTtAZYjbIbJcWr+fOLLUWhBe+CcrM+LhmSWePnwxgokYHSU0yz424LBnkSQOC1B3SYuf2PI70SezBxUyb0l1OB+qkJhKwMxtKEfPCgfdRiUiHtyS/UAUglBlHD3l7BaeRvDgXv0WDu0M+udmiPTl29XD7Ng45Izmz2QXz9MUlq/9EnoTOSHhJJ6R/OZ3SuUmDKXjBwIqXjUzaCg3t+vNNdJxq33jeMpHwE3XIHBulcJXfsHZjGJjoNNkwVhUid+9kNeeC3Qee77rZozcIJyuRvp0u/X+nuhUCc+RWhLbsumJOPBiHvfD2xjTh33rGadjxGPfB2ih4utDLflsoBHI8gYHpVGKEawLCcIrvfiFjwSEygHw==
  template:
    metadata:
      name: mlflow-postgresql-credentials-secret
      namespace: model-pipeline
    type: Opaque
