---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-postgresql-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    password: AgCgfXGTHD/MPHd+K5MY1CDVueoncAHv3MF+b97dS8vBDq7l9mZpk/kIdKp6GZUSyZg9eenl/iWlLoGQWwMuLgcRNlR6rIsKYd16wdpswoYxcTY9MeG2nZ9WPYOZZZi87WQ1pv4CgdyUkM99SQX4jMLbHe4pnuPdZS/pLlcTUZebkIJad6D8IBTqsep3cs9oOZonJaGdMAPiMJO4LMq0/WHMPlrWfbdo+t6b+J+y27W79Q5OgEftUJlTgbH2HTBjjPbx8O/K1yI85PKFxBU/5PXXgswamUWPILVpuB3stzixLWfWUHOGUP8gpeH5xjt+QGnO4ofL8gM5mr0aELZIWweYrHLmv9KzMBkKt90wtjL6GmLOd0kquhJKCaNEPc2e5+/EzA6HtvKCxDMZYfbcGHL+lMymUS23bugbDv5OSzi6wKk9VNIMSK3EjQt9xLVhVRNH4pjIHjmLLKPCptgXjchvS7HYuoxM7dUVrX6Oqu5wGcxno8ye/laYUIKEfukjKCoSLhS8tEsYqt6roro8fYW6ypjmE58e+1Rx/C7EjuDxVB9A56biDBNSCoa9eiAP1rpLZj3q1Tp8xbpi1Z4dsh6Z9z7bZqqHVlbSBPUItcOf9PjgPQCZlRXpDfp7kw98RQBic28dzJ8q+Oqa9sD9uClktTFaD86EMKww6aJ2PHz1fj1BiQfNF+ykOpYVVhAx1G6S8jSheEKPyBiYtdX2LzE=
    username: AgCMTicKlm6twjjupKIo4wnY15gEmRQgKbcL/I1XBos/vlnbQRtFwFLziNyUwV76nbwiUwmFh3pDRnI8Sr6vhkQPqClLcyHyvPLF72Fs1vIVH+6o6bQiBVxVcNDS6k5tKfcHg5I/ipbT72rq/wfSa0HNBMyJ6IuTqydFe6iXmRbPXaVrMfaSpIYLa8nWETo+jrhjip0b1fsyjhOkFgtMeb95Az44rQZrVt0v5dgsmONiupuMh4VNrVd7vtakPB4/3SOLZfpTk/oHKyybPHDbsIA/kFcj1zq2jauBAYA9uucsdmyzjTQFQ31/wO5+6AVt5Xhu6Tsmg2So4l9kcEjmHLTqQ1sbua+Wq97XNfdUedUQKvCpSlrgSANOAgJKU7MyTH7d3iOde700uHR1EneFFr4py95D4tCeSOj+mHQ1s636Qrk5xou/yiehSbA1UepT0ucrOdpKzc05K6lnQZ6x44y0S23Xt4LnXRH+qjA4UXUj8rQFjHae/V1sJ0f+a5HfMczQEvgmfNHnCGPJ1ZLpu/ssv1U8CraenlEzFHuxH08FHxKVMHPMLsTJ3THsihWrYJ018tkPEP9ePTBzZ8ubnP5GZGSWmb5tbd1uoYS9sJPRz0uM9HPyjeQraA6oOgrkq09oiSqx057y6LGlOKrUKd79+NIKT+Th89KQeA67XOOEXIGVfr4IcebwOFoLD4FcHSRNi6VgkA==
  template:
    metadata:
      name: mlflow-postgresql-credentials-secret
      namespace: model-pipeline
    type: Opaque
