---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: phpmyadmin-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    PMA_PASSWORD: AgBailxtnah5YVi1D82Sx5WLRR1L6n58uESLD26wYR7AAxrnbXXBTesNSVZO8xur2HWYmUCWmNDypcQegmXsv/SdZeOvCZDTD+qMtzx+0Ab2nUhTMiZsGu81xRASPxsWuatfMreaLQ4/WH53ooFI4q0kEC6qDyrupHysXejILn64Xky6LNaxKVqzMcJf73bxdNEBIHizMEr+KdtnjdA2RkovX9TEwsvW5w7MHwo2ZtBiJwEppoFY+WSJBbwYJ4WMaUJpCt+N0VxNShjX/r8A40AaMT/P4K3Rbi9OYoJyGspBYAjsdo6wenPOlTzN2UKGtoGyynrJsX5pVsmD9OwmGnS0r91R68j35hBdkgfS0al3k0HB/yvHyIionbX9Re/jDzisX4Xq5k6EnlBspVfGa56Bdhg+8glBgMJMTgAsnC/bcb+JMo8+wiPY7m+ELuNxtDYkXf/io0cu3Z6uTcv+JyYJrYZax2xrwAJHJE58e4oH2ws7EQEVZjKufi1LRsXuooMSDftKTRm2kFOeNJEw8qVFmJDkw1IPo2THYF773kjfNjNo3avg7ddARKqmm9Iyg9yE3A6ipqlQpz6NpgyyZEmju3Nqir/wnMc+Q8u93jWnH8WB4WOsF0PpGmgeGar90vH5Lzey4LGayXSMUUWYAsuCxo8STToC1UH6yW7SSif7KLurVV9QslIyQd4jm7E+kjn8+cTA2xw1+S5ouUbpWl4=
    PMA_USER: AgCmGXJ9ydUSIsgItCKNwzrxDp/eqDiDo03c2ju+87kLlrHsC+Lpun+rcJyO38HVQm/62uVAze5ErRtboK7KYWV1UvaSiiN3aHMGqUV53YyYMcOkR7JFfH4IlUJ7NG8BALiXSkXaTg+1PT4pnF2v0sy5jW/HmYritHse0w4gR2CgA9RFHvuhtT92fS0NGcYs1Nufcgp9fwqU92kaRV0V+jicI2NZIT43UMmfYT55pyHXPbng/29OfAyhnvXMkAFVjX7A2sOVzYev7LZB4E+8rpm4DkNvLf6Nlp7yyLTUlSki/Cxhod8MWM9tVb6ZAoDjSIfg/bH8qW+fK6m8r8Ze3nhUCdviLSU7+ZJHdseXexDoWHeG89BekjH0mfyPzT8ejrkQ7yIx9O9R23roqTlWg2uUhhZgiaPJ53hcHl7+ebTsf945fqAF+46z6sncGABm3VpNiodhzzS/LRYiIdDmv8um4LVzctTcd7gSdzpcWSTMYNVtEfjYjzvBbv03Awgv00AdbGhWQ2vuenqsaTsXuLiavmmvEYidW58xlqSFDHDZVLK8Jrjz6qGvThWl11GX2MjFQYkpszF/we6aEX9Mml37E/2hiljApbgofL1xN9xcks7mdqyo0pme6x94RIckDfxWm1OKHZPCu06bzC/ijlJsVGlYviaozz/XTY1ZA1Fa0XxB7Vy2tPDLNmHUoY6LywMdG4c9rA==
  template:
    metadata:
      name: phpmyadmin-credentials-secret
      namespace: model-pipeline
    type: Opaque
