---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: phpmyadmin-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    PMA_PASSWORD: AgA6IpDZcuoQC74Z016lhfwRkbHxhygbAv78h6oxoZdPMSSkJDZ7/sMwicinkudfgziuUUDZBEvpcJJIUoEtPxFWQy/Iy2eCU6n//NoF2KBs0ZBdvEJpgZt7Dxf3NofbZxINnv6GS2suKxLNvR/Q6282DoveSO8bnUAaOF/qj15ABBrJc3RZkDNMK6w0L6JIFagAkxdp7EU26qVlMDyRa1c6WQ5Lnbu7MvE1QXCaiAYNJZh5Kf2rNXte8P3GwINRdkzkNg/lzVw4e6IQ6ok4Aq0wN94SCgfb/6WlUw2L8GdbfTQBNAk+jEHpbkmaAPIxdAQOu4jm5in6hBlRMTj2jZI6jiryIx1HSqQuGRqFmVcATXgkoi0/BAQFuaBSMIimpKO2HzYIIOGFYnogYj+jaf3q7ENqiks7eph9uXHzeHrqdvKaZtp708t6bVMRE4X2GyB7YLa6dsOqJgU8RXF/NredMIEwBzB+LOUcrVB08QVUmqvIeNJ3ayk1Ol8deCBqP2HkcBDI1PePqYtmVeesS6kbhtG4FK7wlIUDoXR0LBiHdo+tf2cGdPYGIfGoKXALYRRYcrm68kQ2VqJwrMiikZSuBa0OAl9QQybJTLKfQ5mM+8Yo6nSth7RxSNz/HmDnc6OWDVPDtLC0wq570dFF6PJUteeYSTINY2+Dx5uUQ7/PNj7jxQim49TWQQqW9hpy2jCkDB70AQyzvjAAtr97AGc=
    PMA_USER: AgBl054FwHchcWeREvVH4EePOO8mGqt1/HjiRH7tbZx/bj5qlhxve0kaLaEnLd7lMYXHLMdHfR6PaexTRA76NZaLa8thAQvKmpOBBFzTOYtCgqMulKbZuUPkzZZQzHpfbxssZc4Fjj8z5p17Tuxy1B9pLU7cYrDsS0lJBA8MNekM+ITK/+0fFChBDjMnc5Pu9IxZoRk0Cxk7cvBzwSO49/PWgQs9NOBeZsSbwv65PgDYbq3Di+6lNJaoPXLlMjTbkIpnRfU3N1z2mhj+UQTWAVA/QEI+d4PSd9Xzekbf3qNS9VFSDrUVOlCCzbSAmrPtpr3vROIZVmKTIYLK5DNI9FetyoODPR7T8g1yTwD9fvnDaKFTgmtqq2ekuQGwMNGDAvHjksawkn4kKgD1ihLWJk43Xu56hl2ZQ8Ucx/U7k5Fp4Qn/gduln/Jq3YnSyMm/+aeOxRM2J5qjR5Pj3qms80WPns65AjwbwdEaBt8wAHSjPaFghe62Q87FDEb+mX/u6jx72ZLHBLgqu0DskR1unMWrtCBtSCZk7Cmas2UNcrujbQBeMl2fPKMs0JvJF7kzoYpkwjOfP7QilwAXnZQ5bFqBLOLdujf4xrMuXTcmHo5AJkU1VRuA63dphlMY9JqTUZf+wv1mEaSi0phxy+NDBNbg3Tgtmmy84QsSs7xojc6Iz4+cUFHwR5GyM8fLykJz6GH9yx8p2Q==
  template:
    metadata:
      name: phpmyadmin-credentials-secret
      namespace: model-pipeline
    type: Opaque
