---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: phpmyadmin-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    PMA_PASSWORD: AgAucZJyFpqTyfP2EpwqP1zO2Pvs/epadL4mdmDghJZshbeiOsO48MYwmec5T8z9AwuazgRy00LgApO/uGCV1VQp1Pmj9oLkHJqi6SEoSde2CyiWLr/Q7FufNumATM10K9HxM6lMGtastiPOSJVwiJyZglJa9yU/O0lhORfl9UeCi4zuDkKWxfVMtDwNz0rb8OxdASKfyR2eexAr4kTF7txMWNg/Y4n5jem7G/wlbjzFcjYpQSsehqerypN0nctp9piwJ3/Ls4IkLK1caC+OV3UK9Md/5ue20NtsV6l3YFXAUBWSMxMWGt4STkZb49GUobWSIblatjk22I/aC7gur+UYKSmFJjUUP40xYp5S6NFDm2jqMANtWs4hNwLDcDHUOicwxkT0i47MgHrpoSNj2iYoj11+eqVhTAQoF357IpRQLNM8vnLKBek10DugzDjXfrTLA99Kdb8wpKttPtbRIhJyFoHCURRXpXO0n6GJK3sc3pmfsVybn7bD1/2blA+sRMWZum5sDgFxWDMiKF2clAb8hkqGPSbtg3fIiZm2YBOh+WRhzsT+MJmPTsITWpvxs+91Gm5NbLWtYwf7hv/XMFyr4p6t3t6q+Wh07Qo3eXdUL0X8Q/JiN0hkT0A1VyVc8c7rFXR/Fp1Ak7wq0N1PYP8D0Idk9tclOBPlYS2ZO4fEwHeDDrTux1URKTIVdlrjZvhW44mIcTj119w4MJcNINY=
    PMA_USER: AgB0QB+7Q5GgDoIyJe17wxtViKvDoJpWY5P08MpXvpvK3IXWQmDoCJhiD5bdffJERMfhGpcLTrqLbXQuEr/iExG8xu39lac5fijaowmgB4t094bxAzVt5SHPm4ry8uTraup/Jd5lhn0heWeskQY8l4/nV1Z5ku/yqyOqWrCmwieEn1QJMfiQ8zJ/wQab6igf9I0dK7ENdmGBnoJD3yzVS4IwtwCFbRjdFr2zyJ6k0YfQrK59Wss7wrPEfPQOwofh3itWxt4505LG9tczsnrYqQTpj3og1uVzbkD6MjWusRthvyCnepfdZW/UShy4kOjHTmP0W/QLH+sc2X4cQ+6f0E6HfkLngrPu3FBpWsCVlbx3tdxJZN5cdo2ZZSxOAGwsqGIERDo/SV7T4Fwydj3PlIf7v1g0hCirkkipA7TIhojS4crm9nNfaAtLrdQEDYZCPUtMdmQN9IohQ2epzRbi9itvhtkh/mDrFqakEjtsXOF86W837h293SJnj6VaUemsVeI45xjMgqicY8n6FrmiAOe9t1T05/plGsaAs/W9aXK+3R8t+2BKSXInIfWJ7ovPX/hRB2Sz8kojDUDEQJJVWUl+14RpXTock/UESpV5bWAgrmwl72Lrm38N43n8WmZv9JmeZ7HkzbDJ+JFpP98Voc82sAaDeErWSPYDgNWQCNMnfaIs+NqA7Hs4meIfzlxnxNmVv8w/Rg==
  template:
    metadata:
      name: phpmyadmin-credentials-secret
      namespace: model-pipeline
    type: Opaque
