---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    password: AgA7Fv+Ab370285aSNmOuXxlZ0fGWg9Ct1Wv1oXvoARYqfIRWM+EhlNOv5XHgv/QmexKOYoQ2LOBwE0xYtF5a/UTOwzAqOevUFvJJLAjirJy1sLT9t/xCZmFI3tMHExCGsYzk2px8qdpHePfe/ySgGS/MlA5bTZ3vPiAKwjyDP6VinsKvT9fxx77VGd16xI7X2s7TijVa/8ZzvoJhVjNxYaOgk4GUg23oq/GIKF4MLkGmXyfoIamoR4o5TX+IBHQyhIu0FJSOfceUIBdWon9T57mDzXGAHyJbr8oX8Pd5ub/XMqvHEnLTkPn/W2+QEmxgmjm/xwgPMBFX3q7iByK4oTCCIvwzqbHVdTnFs2ZNlDmFYN/u0O50Rre3rQsK2TIeHknQyu3LagdCNte4bbTNwLtbwUMYQq70TvzJzvnGD4F6/sJobgLv6PgTzOh/l0/QdQr2wH6nVmAuVo66PSlXF/Mw5Rt9Ux3dZq/blGQdGm7CCJnU+rsENKGI1Ome6aBSnb9Ty+pcrh6qggO4hoxtF6lEgoBcoGSFOcEo6ElE0iIHrlKq9i9/q6dQLbwttsXcwBV3tqO6vs9WgfcZj2wRS037RijdGBIrT8XD+IjfMNUQCsnf+J0+ePTrmQiMKL0emUOlDUtoEZ7LQ/GmhWJlgjWSrWRZPRYApHsHA/U1Y5IuRK9hcpH5a3unX5ZbRXE2Sar8Ji/ML5E1KPqiEfe85I=
    username: AgCfUNe+thwAT9htJNqKnoxEJhOypZQT8VU5Dnmp0l1wGwgONQvW/9VinXD4KFs5s4KzwfeQMsTfAfKglegEHtVMed59e7XBmKMP0MCaQK+kkfYBoLWUBVxL56RAusFeYG3CWHE/umf6m7xgAbLVRCD147TF/hGyCfi+FTwFL5bnVikQo3RmNxhviz0QMhWyIw5uesFGBfHaYJgGBQM+Iii6XJxaUHojG4c7b0QVdTu9ag0VeY7VZ5c6i0zCzcGeQY0WJFaTyzCD3M7ancim+PimxPW+uZAKoZpIsKNSn+m9/O6WuLW65785Bu9dcfktwGYaUmmaCtrEUa8suKfVSuPY1JW1uCiZx/vFMcraFAZhRHm7BqvGfz0MUpN6HopBigcTBiaVohiL823tHqljKsiWLZ1ecOxCwh91JxcDY44/LAtK6BAs6ZE9Oxw7moLA9w45zv01ULH+tgTfei4HHI9kYL6MlDwBhj7kIsBGzdM3tptDDXOdqV9cm2iDBVobi535IN4RPZ8Se8Rl/nXpYAc5CcD3IjC4Ck437A2clgOwCiE4el5IwNMG3gaWGBGgSTa8EDsPyTv8hu1ndde+7F22ftDp1t8usumxaf4WJTcGkC37+rkzpxTHfygi7s1qsknoA8viEYixoL5rUoMaAmfUQv8wkxwkO8KAT2wRtpx1A8RS9ygGPNXZML/Wn6Yy88tSrw0qvw==
  template:
    metadata:
      name: postgresql-credentials-secret
      namespace: model-pipeline
    type: Opaque
