---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    access_key_id: AgAT5XFz7YTXHFzNBwcizpu2co+kdAmlDT/VgQCr/XOfSMDN/+WFaFbxh8UqWh4TilJUK7u7qrtQR7vQXklWYbHvCOvaalXefibX+BNSHo8P7QTxiCL+FfVa/9GBo0eV7sqnu6Vmo5qruPj2GZSZWuLzzpyhx4ZjbGBZmA0nsUuEKeNxMSCKeiX81x2haHsVXNl7QxnS18l2nHhV5zB6lt8JJhS/gju3y1l2+bIbqUgvjQcwaKZloDsY9WfRkFtncxDfewE5m/rLdZx9S10a0MPt1J00mkD9bhU4yjyS8wifcmehUpCQ1cMc4P1WOn4q5NepAI5EFCa4J9bpZXF8rGMKTdgSdMYd9POMdoHn+9+7HFrQE6yf59i9m1vJCFF+UVLHbaLgpMmLBGymeKXe4utzR8YX0IQci0YwnEkCDfQXnrbQxG08xn4lGWknvgTpn8jGOObgx8VcMLVGF1p2B+BWg3u7ztqzqHNb9DLP+VG3zNWh22Arlb+o3mOC6LasaB3CrNlO5HnFYAzv6YcuwWvNFhBXZwrZKgdYPsJtgcRM8R4IQ40ompLCd0tOqQ1bN6S8BlTwvO3ngZDl3wnsTd2ai+kZ9if+VA0txG803IRiLhBHjfbKKn7OMBKpIzEJNnMNwThVko3ahQusRWQMXOhJn3vZ8xS2CDG1cpBXNkODTI8zMYkGxU3DgOn/kiKgm71hXq8agw==
    secret_access_key: AgAgR+ME5L3XvbkVzOSowYhhMYKj3lq6jO+Z2nsJYN6r3ZOfdgWAKE6W/z49boHdPHEI9/l36Mh6t7W+qBQ3IscEzwRWl6x/M5jLb6KxphE0ZmMFEvONwWTYEIblCYzuzufm2PTozktYktp+BlhuLmnxueDxtzuuJbhqTAgjSJqpjdzOi4CwHJoq36Nm6rMGYZ4169CDMmPTZu9tE6owoz5d5dkUZgHULpk7ZGEVe3vB8opppDCwaZ7KjFzmazboqP34wQzUTgk0WC97ltH5mZwETBCBT8xe3br+617fxFWCFSpzyTsPO/smq/8mLoS4wqLr6pnexrClCTur+wSgj84gjYAeZ7+YQXr6w3fErlsIqAX3XumEi7v+FIq+FfLsfeJEnGy4Yc3uj+BoRvxKody0KFQ1C3tdKZOahu4fB7QUE7LI77gA4qYzJPjAQiGNzj5oCNZGWDA3C2EwtDxEMv336r26iqO0UIqHirg/jisQR642YSIuZk9SwTaIvchG29K9NVJrCH59T2ZjFNrTEcpPXCOM/ezFFN4GKf/cb5qIaVGhHqVqdvah9exM0KSKCa/smfDlpW5lFfNy/PozxnFrOB7ANSzV76v8XRww22OhKJ6FR5L4xNxkY70CsVwaLWFaVdBTOSJVx9f23/qTXRbn7irlrcMSIgkLSiQwAPwhR/iJNxcw1GiszVkvyRIZDK7cWRcH8XHmsw4kcRfcL0U=
  template:
    metadata:
      name: rustfs-credentials-secret
      namespace: model-pipeline
    type: Opaque
