---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials-secret
  namespace: model-pipeline
spec:
  encryptedData:
    access_key_id: AgBEZrhnxQOqybtNaTedj9aly9eMSBwqlObVlAqJNggsAHJH6pIicFM7ognI0uo2ipxE5yh1egSHmGROUTcAI+fU1onB5igAAjcyAejgQ5NQdTFE/+s6FYorXiflKdKilnIhtLOVEbEFclpY7WoRZ8TjTGqJwFqknID9jqCeBGMHcmzHBJxyQOSuaoJHCgSnQpU3NflXxgdWk4Qe9ZUTNZsP0szy/qNGOH5xx8H9CsGO9Zsr+EM85dnsE+r7QXA3c+gU4P0kmbKCz+jUnB8DaYmaOav4uuIXo5QTPMB/QJQKFbxLRA2m36iP5PjoH5d7UsZz74JaWfGfrsJsJ70m7RLb6z2SEhRQOUFFYc/qo3FZO60y9vUTdEoZ30/hoHewu8G8x3ROt3V+t1Jmm2VDKBqpNuXAldy1of/dco2JJfxbirh8EAav2/WHVT/ItBVmHy8RsTU5J9JRHwJaJ1VSUM9FM5oJ8ySSF8NMmEIi7DwUGCKwOFGeawUZ8kvRw00P7QROGKWwh7g6zwjgJhWgumEm47JNTKDNxkxkl7FRZj3+0sg9BcdsvjuRNEAV8RqGlrgSyttUFM/feFTggM7xPC8AvLJWiIT/dQABiSIYDj4Uc1+WwcTawVyKw+oeX90tqYKKvMCQaAB77bbe4f/QuzxMQAiWa9a//a+eMF761W2T9wpuA+eBMT7JTm7vbMBoLLtqY/g2IA==
    secret_access_key: AgCN8X6svL/Npjw/fFIpElFiV0ha0K/1tXqiIoohdhglbMTD42bKaJnphDDCJbZsPt5WkVv0gRxmcbRPsGoEN1uCaMan6t4qPjcw3as/e6PyXYy+t1u6V0aBw5zYcGxLT3XJo8ai7vPZl1vneQ61rxaSM5YqT9N1XxnVxPO9oPteNMGhw0nmbIjlxQ1WGjE0mOKDeYgtXC8w601Q2ToHObQURzYaEpOBEYW5LUwfvMuY2l+2XqdftS+0xHv+XoGsKuyNJnZx0Euuzhzk0orORB/gJAnhKWQ+syC4HR+LvSHsSsGotVKoZPAg5hpiUPRQ4rbNelQEW80SkLF7RGwH3HCTxEdaalc30/RxZldY7MA7JmQcPOnOSLEI6AI3VCL37N3yWeoYVJlxNIN9ZYgE1JGX1v93D761pYYEgUGUce8WCR/YNV44qRAi4pz4ATg0hQVKSbObd1MOcN0UB97JLa8cEN+z8NlfPTtSTas4/UWp1p/dUPnIVx40N1v/3Zm+/OveyhwZMS8oBdPQHHKr19uRjOlxKdIZOUatld4/GyLGYuHmzZSinfvYkEXFU6691oZN01yFOVyWxYda53qQPNgRsebH2dLJ/8bKBmGDpZ4O8qPARizD7QtMqVAQtdVMH46aQ8dxWdZekF8MoheJaDo/2kc0Wdoq4Wp4MDHZRxifKFpzdck5hMCJqN+MbZ8XhDaLwA/R1YdzjFoVrk3SqOk=
  template:
    metadata:
      name: rustfs-credentials-secret
      namespace: model-pipeline
    type: Opaque
