apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  namespace: frontend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
        - name: frontend-server
          image: mysticshirou/icantkube:frontend-server-v2.0
          ports:
            - containerPort: 80