apiVersion: v1
kind: Service
metadata:
  name: rustfs
  labels:
    app: rustfs
spec:
  selector:
    app: rustfs
  ports:
    - name: api
      port: 80
      targetPort: 9000
    - name: webui
      port: 9001
      targetPort: 9001
