name: Build & Push Images to Dockerhub

on:
  push:
    branches: [main]
    paths:
      - "src/**/*"

jobs:
  list-changed-directories:
    runs-on: ubuntu-latest

    outputs:
      changed-directories: ${{ steps.detect.outputs.changed }}
      dockerfiles: ${{ steps.find-dockerfiles.outputs.dockerfiles }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1

      - name: Find Dockerfiles in changed directories
        id: find-dockerfiles
        run: |
          dockerfiles=$(find ${{ steps.detect.outputs.changed }} -type f -name "*.Dockerfile" -print0 | jq -Rsc 'split("\u0000")[:-1]')
          echo "dockerfiles=$dockerfiles" >> "$GITHUB_OUTPUT"

      - name: Show changed directories
        run: |
          echo "Changed directories:"
          echo "${{ steps.detect.outputs.changed }}"

  build:
    needs: list-changed-directories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.list-changed-directories.outputs.changed-directories) }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     file: 
      #     push: true
      #     tags: 
