name: Service Health Check

on:
  pull_request:
    paths:
      - "src/**"
  push:
    branches: [main]
    paths:
      - "src/**"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: set-services
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.event.pull_request.head.sha }}"
          else
            BASE="${{ github.event.before }}"
            HEAD="${{ github.sha }}"
          fi

          SERVICES=$(git diff --name-only "$BASE" "$HEAD" \
            | awk -F/ '/^src\/[^/]+\// {print $2}' \
            | sort -u \
            | jq -R -s -c 'split("\n") | map(select(length>0))')

          echo "services=$SERVICES" >> "$GITHUB_OUTPUT"

  healthcheck:
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '[]'
    runs-on: ubuntu-latest
    env:
      hasFailed: false
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build \
            -f src/${{ matrix.service }}/${{ matrix.service }}.Dockerfile \
            -t test-${{ matrix.service }} \
            src/${{ matrix.service }}

      - name: Run container
        run: |
          docker run -d \
            --name test-${{ matrix.service }} \
            -e MODE=ci \
            -p 18080:80 \
            test-${{ matrix.service }}

      - name: Health check (silent)
        id: healthcheck
        shell: bash
        run: |
          set +e
          curl -s --fail --max-time 15 http://localhost:18080/health
          STATUS=$?
          set -e

          if [ $STATUS -ne 0 ]; then
            echo "hasFailed=true" >> "$GITHUB_ENV"
          else
            echo "hasFailed=false" >> "$GITHUB_ENV"
          fi

      - name: Show container logs
        run: |
          docker ps -a
          docker images
          docker logs test-${{ matrix.service }}

      - name: Fail job if health check failed
        if: env.hasFailed == 'true'
        run: |
          echo "Health check failed"
          exit 1


      - name: Cleanup
        if: always()
        run: |
          docker rm -f test-${{ matrix.service }}
