apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-external-secret-reference
  namespace: cloudflare-tunnel-ingress-controller
type: Opaque
stringData:
  account_id: xxx
  api_token: xxx
  tunnel_name: xxx
